### ISSUE TITLE
Allow showing user meta in user list

### ISSUE THREAD

**Issue by grappler** [wp-cli/entity-command#101]
I am running this command `wp user list --role=school_member  --fields=ID,display_name,user_email`

I would love to show the user meta key `school_name` too. The code at the moment does not support adding a meta key to the fields.

This is partially to the restricted fields that I can use. https://github.com/wp-cli/entity-command/blob/master/src/User_Command.php#L34-L41

I can't also use `all_with_meta` to show all of the values for the users which `get_users()` supports.

**Comment by miya0001** [comment]
Hi @grappler 😊 

I would love to show the meta key too!

Do you know example commands to pass the keys to option like this case.
I am thinking we can pass the meta keys to add `.` as the first char like following.

```
wp user list --fields=ID,display_name,.school_name
```

But I have no idea how should we pass the `all_with_meta`.

**Comment by danielbachhuber** [comment]
> But I have no idea how should we pass the `all_with_meta`.

Oh, I see. `--fields=<fields>` conflicts with `WP_User_Query`'s `fields` argument.

**Comment by danielbachhuber** [comment]
> The code at the moment does not support adding a meta key to the fields.

In testing, you can already list user meta:

```
$ wp user meta update 1 foo bar
Success: Updated custom field 'foo'.
$ wp user list --fields=ID,foo
+----+-----+
| ID | foo |
+----+-----+
| 1  | bar |
+----+-----+
```

You simply need to define each field to be listed. `wp post list` works similarly, because both `WP_Post` and `WP_User` objects pull data out of meta when the key doesn't yet exist.

**Comment by miya0001** [comment]
Oh! I didn't know that!!

**Comment by grappler** [comment]
@danielbachhuber Sorry I could not replicate that.

This is what I am getting.
```
$ wp user meta update 1 foo bar
Success: Updated custom field 'foo'.
$ wp user list --fields=ID,foo
Error: Invalid field: foo.
```

I am using WP-CLI 1.3.0.

**Comment by miya0001** [comment]
It worked on my environment.

```
$ wp --info
PHP binary:	/usr/local/Cellar/php71/7.1.10_21/bin/php
PHP version:	7.1.10
php.ini used:	/usr/local/etc/php/7.1/php.ini
WP-CLI root dir:	phar://wp-cli.phar
WP-CLI vendor dir:	phar://wp-cli.phar/vendor
WP_CLI phar path:	/Users/miyauchi/Desktop/wp
WP-CLI packages dir:	/Users/miyauchi/.wp-cli/packages/
WP-CLI global config:	/Users/miyauchi/.wp-cli/config.yml
WP-CLI project config:	/Users/miyauchi/Desktop/wp/wp-cli.yml
WP-CLI version:	1.3.0
$ wp user meta update 1 foo bar
Success: Value passed for custom field 'foo' is unchanged.
$ wp user list --fields=ID,foo
+----+-----+
| ID | foo |
+----+-----+
| 1  | bar |
+----+-----+
```

**Comment by grappler** [comment]
It is strange it is not working in one environment but it works in another. Another envoirnment where it is not working is 

```
$ wp --info
PHP binary:	/usr/local/php71/bin/php
PHP version:	7.1.10
php.ini used:	/usr/local/php71/etc/php.ini
WP-CLI root dir:	phar://wp-cli.phar
WP-CLI vendor dir:	phar://wp-cli.phar/vendor
WP_CLI phar path:	~/www/schtifti/staging/releases/20171005103803
WP-CLI packages dir:	~/.wp-cli/packages/
WP-CLI global config:
WP-CLI project config:	~/www/schtifti/staging/releases/20171005103803/wp-cli.yml
WP-CLI version:	1.3.0
```

**Comment by miya0001** [comment]
What is the WordPress version?
I guess behavior of this command depends on WordPress core and plugins which is activated in it.

**Comment by grappler** [comment]
I am using WP 4.8.2, I even tried switching to Twenty Seventeen and disabling all plugins.

**Comment by danielbachhuber** [comment]
@grappler WP-CLI expects all objects displayed to have the same structure. In this case, all of the users need to have the `foo` field, otherwise WP-CLI errors.

**Comment by jupitercow** [comment]
FYI. If you use `wp user meta add foo ""` where `foo` is the meta_key you need to list out, it will add a blank entry to all users who don't have the meta_key already and leave the ones who do alone. So you can use it to clean up the data and run `list` successfully

**Comment by drzraf** [comment]
> @grappler WP-CLI expects all objects displayed to have the same structure. In this case, all of the users need to have the `foo` field, otherwise WP-CLI errors.

Is it possible / desirable to make wp-cli more resilient to a scenario where some posts do not have this metadata?

**Comment by danielbachhuber** [comment]
> Is it possible / desirable to make wp-cli more resilient to a scenario where some posts do not have this metadata?

Oh, it's certainly possible (anything is possible), but the cause is deep within WP-CLI's internals:

https://github.com/wp-cli/wp-cli/blob/a5336122dc45533215ece08745aead08af75d781/php/WP_CLI/Formatter.php#L217-L238

The formatter API wasn't ever designed with this scenario in mind (objects with arbitrary properties). I don't think it's worth changing the formatter API for this need.

An intermediate "fix" would be to add the property to the `$post` object if it didn't exist. However, this seems hacky to me.

Personally, it seems like the best approach is to `wp post list --format=json` for the whole blob, and then use `jq` to pluck the fields you want.
