### ISSUE TITLE
Nested Array for Pluck Option Examples?

### ISSUE THREAD

**Issue by wpbullet** [wp-cli/entity-command#106]
I am loving pluck and patch!

According to the docs it looks like it should be possible to access multiple <key-name> values

Here is my example

`wp option get wp_bullet_lazy_load_filters_tab`
I get this output
```
array (
  'disable_first_image_post' => '1',
  'll_skipped_pages_list' =>
  array (
    0 => '/fixing-wp_options-table-missing-unique-column-primary-key/',
  ),
  'll_style_classes_option' => '1',
  'll_style_classes_list' =>
  array (
    0 => 'textwidget',
  ),
  'built_in_classes' => 'none',
)
```

Then plucking

`wp option pluck wp_bullet_lazy_load_filters_tab ll_style_classes_list`

```
array (
  0 => 'textwidget',
)
```

How can I access this array's values? I've tried variations of this to no avail

```
wp option pluck wp_bullet_lazy_load_filters_tab ll_style_classes_list,0
wp option pluck wp_bullet_lazy_load_filters_tab ll_style_classes_list[0]
```

I figured it out!

`wp option pluck wp_bullet_lazy_load_filters_tab ll_style_classes_list 0` outputs
```
textwidget
````

**Comment by danielbachhuber** [comment]
Hi @wpbullet,

Please use Slack for support questions, thanks.
