### ISSUE TITLE
Add subcommand for checking a user's password

### ISSUE THREAD

**Issue by vbaranovskiy-plesk** [wp-cli/entity-command#110]
Hello,

I have a question about possible new subcommand for 'user' command before i will try to upstream it.

We (in Plesk) are making an WordPress Toolkit and we have "login" button functionality.  Before log in to WordPress we check admin credentials (stored in own db). User will be redirected to admin's credentials page if stored credentials doesn't work. We are using a self-written command for this purpose but this command could be easily moved to 'user' mainstream command:
`user check-password <login> <password>`

Is there any chance that such request will be approved?

![Uploading login.png…]()

**Comment by danielbachhuber** [comment]
Hi @vbaranovskiy-plesk,

Thanks for the suggestion. It seems like a reasonable idea, I'd be open to a pull request for it.

**Comment by danielbachhuber** [comment]
FYI — Here's an overview to our standard idea generation workflow: https://github.com/wp-cli/ideas/blob/master/README.md

**Comment by vbaranovskiy-plesk** [comment]
Hi @danielbachhuber,

thank you for your answer. I will try to make a pull request in a nearest few days.

**Comment by danielbachhuber** [comment]
@vbaranovskiy-plesk Still planning to submit a pull request for this?

**Comment by thrijith** [comment]
@schlessera @gitlost need to clarify something, whether the output for 
`wp user check-password admin admin`
should contain a message like 
`Valid Credentials.` or anything else ( confused )

**Comment by gitlost** [comment]
My take is that it should just `halt( 0 | 1 )` like `wp core is-installed`...
