### ISSUE TITLE
Add a means of fetching the permalink to a post

### ISSUE THREAD

**Issue by johnbillion** [wp-cli/entity-command#120]
There is no built-in means of fetching the permalink to a given post.

The only place where a permalink is exposed is in `wp post list` if you explicitly include the `--fields=url` option.

I'd like to see either:

* A `url` field added to the output of `wp post get`.
* A `wp post url <id>` command.

**Comment by johnbillion** [comment]
The same thing applies to terms, users, and comments.

**Comment by danielbachhuber** [comment]
Previously https://github.com/wp-cli/wp-cli/issues/2070

**Comment by dd32** [comment]
I'm re-opening this, as it would still be nice to have `wp post get $ID --fields=url` rather than being forced to `wp post list --post__in=$ID --fields=url`.

It makes sense (to me) for the list/get methods to return the same data/have the same fields.

**Comment by tubiz** [comment]
I will work on this.
