### ISSUE TITLE
Manage terms by slug instead of id

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/entity-command#13]
Currently, `wp term (update|get|delete)` require `<term-id>` to specify the term to operate on. For developers who only know of the term slug, it can be annoying to need to figure out the term id.

For each of these commands, we should introduce the `--by=<field>` argument so the developer can refer to the term by slug:

```
[--by=<field>]
: Explicitly handle the term value as a slug or id.
---
options:
  - slug
  - id
---
```

Term id should continue to be the default, with slug as the other option.

Related https://github.com/wp-cli/wp-cli/pull/3896

Originally https://github.com/wp-cli/wp-cli/issues/4060

**Comment by BhargavBhandari90** [comment]
@danielbachhuber If we add `--by=<field>`, so the result should be from id, if not specify `--by=` from the command.

**Comment by danielbachhuber** [comment]
🔨
