### ISSUE TITLE
wp post create: better docs for --meta_input

### ISSUE THREAD

**Issue by ScreamingDev** [wp-cli/entity-command#131]
meta_input is listed as an argument but neither is there a hint how it should be used
nor do I find it in the source or in tests.

wp cli 1.4.1

**Comment by schlessera** [comment]
The `--meta_input` is one of the fields that are currently just passed through to WordPress, to provide arguments to the `wp_insert_post()` function: https://core.trac.wordpress.org/ticket/20451

However, `--meta_input` requires an associative array as input, and right now, WP-CLI does not provide a way to enter these. I'll create a new issue to revisit that topic, as it had been closed previously in favor of the WP REST API handling (https://github.com/wp-cli/wp-cli/issues/1323), but that will probably not switch to being the default mechanism anytime soon.

**Comment by schlessera** [comment]
Related: https://github.com/wp-cli/wp-cli/issues/4616

**Comment by gitlost** [comment]
Closing via https://github.com/wp-cli/entity-command/pull/133

Thanks for raising the issue @ScreamingDev !
