### ISSUE TITLE
Running `plugin activate` without a plugin slug should throw an error

### ISSUE THREAD

**Issue by schlessera** [wp-cli/entity-command#136]
Internal command validation for `wp plugin activate` does not seem to check whether you actually provided a plugin slug.

It should check it has a valid plugin slug to work on and throw an error otherwise.

via @swissspidy in https://github.com/wp-cli/language-command/issues/27#issuecomment-360478383

**Comment by gitlost** [comment]
Moved to https://github.com/wp-cli/extension-command/issues/82

**Comment by schlessera** [comment]
Ha, I mess up these two command names all the time!

**Comment by gitlost** [comment]
Same here!
