### ISSUE TITLE
Weird plugin install behavior

### ISSUE THREAD

**Issue by schlessera** [wp-cli/entity-command#139]
The command `wp plugin install gutenberg --active` has just produced weird behavior I need to investigate:

![image 2018-01-30 at 6 44 02 pm](https://user-images.githubusercontent.com/83631/35581980-afba381c-05ed-11e8-8677-7ee0d7d58b86.png)

Could this have something to do with the fact that both site and plugin share the same folder name?

**Comment by gitlost** [comment]
Is this with the current build?

**Comment by schlessera** [comment]
Yes, but seems to be site-specific. I suspect the folder name to trigger a regex n the wrong way.
