### ISSUE TITLE
Document how to generate terms and assign to random posts

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/entity-command#14]
While it probably doesn't make sense as an actual feature, it would be neat to have a code snippet for generating terms and then assigning them to random posts (e.g. to mock the situation for https://github.com/wp-cli/ideas/issues/40)

**Comment by BhargavBhandari90** [comment]
Hi @danielbachhuber,
Before anything, we should decide criteria for the generating terms. I have some thought on this. 

1. What will be the names of those terms?
2. How it will assign to random posts. Like how many terms will assign to random post?

Add your thought too, if anything comes from your side.

**Comment by danielbachhuber** [comment]
> 1. What will be the names ( pattern ) of those terms?

They could be the same name (e.g. `Test Term`), or same sequentially (e.g. `Test Term 1`).

> 2. How it will assign to random posts. Like how many terms will assign to random post?

We'd assign some range of terms (.e.g between 1 and 5).

**Comment by BhargavBhandari90** [comment]
Hey @danielbachhuber,
Do we have a any other document like this? So that we can follow the same structure for this too.

**Comment by danielbachhuber** [comment]
> Do we have a any other document like this?

Mostly the existing `## EXAMPLES` associated with each command.

Why do you include your suggested implementation here, we can refine and iterate, and then you can submit a PR?

**Comment by danielbachhuber** [comment]
Punting on this https://github.com/wp-cli/entity-command/pull/362#issuecomment-1228736478
