### ISSUE TITLE
Rename the --<field> flag

### ISSUE THREAD

**Issue by johnbillion** [wp-cli/entity-command#149]
Everything is fields.

The output of `wp post list --help` displays the following:

```
  [--<field>=<value>]
    One or more args to pass to WP_Query.

  [--field=<field>]
    Prints the value of a single field for each post.

  [--fields=<fields>]
    Limit the output to specific object fields.
```

I can pass in fields as input and ask for a field or fields as output.

I think the `--<field>=<value>` flags (which get passed to `WP_Query`) should be renamed to `--<query_var>=<value>`. Internally, `WP_Query` uses a bit of a mixture of `args`, `vars`, and `parameters` when referring to the query variables, but the internal property name is `query_vars` so using the singular `query_var` name for the flag makes the most sense.

The resulting documentation would become much clearer:

```
  [--<query_var>=<value>]
    One or more query vars to pass to WP_Query.

  [--field=<field>]
    Prints the value of a single field for each post.

  [--fields=<fields>]
    Limit the output to specific object fields.
```

**Comment by johnbillion** [comment]
Actually, I think core needs to consider what terminology to standardise on. IMO `query arguments` makes the most sense, but internally they are referred to as `query vars`.

**Comment by schlessera** [comment]
In general, terminology is a bit wild in the WordPress space... ;)

I think the other arguments don't match their description either. As an example, `specific object fields` does not make any sense, as a table has fields, but an object has properties.

Renaming the `<field>` would probably not introduce any major BC problems, as it should not be referred to directly in scripts. For the others, all hope is lost, I guess.

I'll think a bit more about changing to `<query_var>`, as this is mostly cosmetic in the end.

**Comment by danielbachhuber** [comment]
FYI - `--<field>=<value>` is a special case argument:

<img width="553" alt="image" src="https://user-images.githubusercontent.com/36432/36733097-627b4418-1b84-11e8-8055-f8183aab34e5.png">

I'm not sure it's worth the uncertainty to rename / change this logic.

**Comment by danielbachhuber** [comment]
Closing, given this is more than a documentation change.
