### ISSUE TITLE
option patch update fails to clone comparison object

### ISSUE THREAD

**Issue by hisham** [wp-cli/entity-command#151]
I have the following row in wp_options:

`|       567 | frm_strp_options | O:8:"stdClass":5:{s:9:"test_mode";i:0;s:11:"live_secret";s:32:"sk_live_xxxxxxx";s:12:"live_publish";s:32:"pk_live_xxxxx";s:11:"test_secret";s:32:"sk_test_xxxx";s:12:"test_publish";s:32:"pk_test_xxxxx";} | yes      |`

I want to change "test_mode" to 1. 

I do the following: 

`wp option patch update frm_strp_options test_mode 1
`
But all I get is: 

`Success: Value passed for 'frm_strp_options' option is unchanged.
`
And nothing is changed.

**Comment by hisham** [comment]
Pluck works succesfully: 

```
wp option pluck frm_strp_options test_mode
0
```

**Comment by hisham** [comment]
Is this because the option value is stored as stdClass? Does patch support stdClass?

**Comment by danielbachhuber** [comment]
> Is this because the option value is stored as stdClass?

Yes, that's the source of the problem.

> Does patch support stdClass?

It certainly should. This bug will be fixed with #152

**Comment by hisham** [comment]
Great, thank you!
ᐧ
