### ISSUE TITLE
Add wp site meta subcommand to manage blogmeta

### ISSUE THREAD

**Issue by spacedmonkey** [wp-cli/entity-command#158]
Now that blog meta has landed in [core](https://core.trac.wordpress.org/ticket/37923), there should be a way to manage it in WP CLI.

**Comment by schlessera** [comment]
Yes, I agree. Do you already have specific thoughts about how this should be modeled?

**Comment by schlessera** [comment]
Just to start the discussion, here's what it could look like if we modeled it after `wp post meta`:

- `wp site meta add <id> <key> [<value>] [--format=<format>]`
- `wp site meta delete <id> [<key>] [<value>] [--all]`
- `wp site meta get <id> <key> [--format=<format>]`
- `wp site meta list <id> [--keys=<keys>] [--fields=<fields>] [--format=<format>] [--orderby=<fields>] [--order=<order>]`
- `wp site meta patch <action> <id> <key> <key-path>... [<value>] [--format=<format>]`
- `wp site meta pluck <id> <key> <key-path>... [--format=<format>]`
- `wp site meta update <id> <key> [<value>] [--format=<format>]`

Does this all make sense based on the current `wp_blogmeta` implementation in trunk, or are there commands that are invalid?

**Comment by spacedmonkey** [comment]
In #159 I have created a first implementation of this sub command. It is a pretty standard meta table, I have just implemented the existing meta class and extended. 

As for merging testing, blogmeta is in trunk, but this PR might be better to merge at 5.0.0 is out, as it easier to test. As is, we can't be use that table has been installed, which is the reason, I have added a check to `is_site_meta_supported` a new core function to check it is there.

**Comment by schlessera** [comment]
The tests currently break because the version requirement of 5.0 is not met.

Wouldn't it be enough to check for the existence of the `is_site_meta_supported` function?

**Comment by spacedmonkey** [comment]
In the test, I have a check to see if it WP 5.0.0  - https://github.com/wp-cli/entity-command/pull/159/files#diff-730a53ee55d6e1e534aa6972bb0802aeR3. This is how term meta [works](https://github.com/wp-cli/entity-command/blob/master/features/term-meta.feature#L3). 

I did those to that these tests would be skipped on earlier version and tests wouldn't fail. Not sure how else it should work, unless I am missing something.

**Comment by spacedmonkey** [comment]
Version number in trunk is 5.0 - https://github.com/WordPress/WordPress/blob/master/wp-includes/version.php#L7

**Comment by schlessera** [comment]
The version in trunk is `5.0-alpha-42866`, which is technically lower than the (released) `5.0`. This is why [this check](https://github.com/wp-cli/entity-command/pull/159/files#diff-fb86b4c91b2edfb72f6eedaa67b568aaR35) fails. So, my suggestion would be to not do this failing check, and check for the existence of `is_site_meta_supported` instead, as it has been introduced with the same commit.

**Comment by spacedmonkey** [comment]
In the latest version of the test, I removed the check for WP 5.0 as `is_site_meta_supported` check should cover it. I also upped the version number to `@require-wp-5.0.0`. The error is different, with it now saying, 'Error: Failed to add custom field.'. An error I don't understand. Not sure how to fix this error.

**Comment by schlessera** [comment]
@spacedmonkey See comment here: https://github.com/wp-cli/entity-command/pull/159#discussion_r176935384
