### ISSUE TITLE
Updating a user with an invalid role should show a warning

### ISSUE THREAD

**Issue by johnbillion** [wp-cli/entity-command#160]
The following command always succeeds. Ideally it should fail when an invalid role name is passed.

```wp user update <username> --role=bananas```

**Comment by danielbachhuber** [comment]
Thanks for the report, @johnbillion. Some follow-up questions (thinking aloud, not necessarily for you):

1. Is there a valid use case for assigning an invalid role to a user?
2. Would there be backwards compatibility concerns in changing the current behavior?
3. Is there other prior art within WP-CLI where we've changed user input validation similarly?

**Comment by swissspidy** [comment]
Does core error when updating a user with an invalid role?

**Comment by twocs** [comment]
This is an interesting but old thread, that addresses a question I had. And doesn't seem to be addressed elsewhere.

Although there are validation checks for the email address, in core creating a new user, the role is user metadata and there do not appear to be checks. It is entirely valid for users to have no role, but there do not seem to be any notes either way about having a role that's not in the database. Removing a role from the database does not seem to remove it from the users, so conversely, one might create users with a certain role, then later create the role to grant capabilities.

Relevant code:

Create new user
https://core.trac.wordpress.org/browser/tags/5.3/src/wp-admin/user-new.php

Roles
https://core.trac.wordpress.org/browser/tags/5.3/src/wp-includes/class-wp-roles.php

To prevent invalid roles and introduce role checking into your site, you can use filters: From looking at the code, it seems that 'can_add_user_to_blog' would enable this? https://developer.wordpress.org/reference/hooks/can_add_user_to_blog/

**Comment by danielbachhuber** [comment]
@johnbillion Still think we should implement this? If so, I'm good with it.

**Comment by johnbillion** [comment]
It is unusual (or not?) that WP core doesn't validate the role, but I think there's value in doing so in WP-CLI. +1 for accepting the role but triggering a warning, which means if you're creating a user interactively and you typo the role then at least you'll see a warning.

**Comment by SH4LIN** [comment]
Right now entering the invalid URL will give a warning than a success message and in the WordPress dashboard the role will be changed to none
