### ISSUE TITLE
Allow fetching raw option value for JSON encoded / PHP serialized options

### ISSUE THREAD

**Issue by johnbillion** [wp-cli/entity-command#165]
When calling `wp option list`, the option values are displayed in their raw format.

When calling `wp option get <key>`, there's no way to get the raw value for a JSON encoded or PHP serialized value.

**Comment by danielbachhuber** [comment]
@johnbillion Just to clarify, this would be the value in the database?

While `wp option get` could support `--format=raw`, is there syntax you'd suggest for `wp option list`?

**Comment by johnbillion** [comment]
`wp option list` always shows the raw value for options. It _could_ be extended to support the full list of formats (JSON, CSV, etc) but I'm not sure how useful that is.

**Comment by shawnhooper** [comment]
Added the `--format=raw` to the `wp option get` command in the PR above. 

The `wp option list` already has a formatter supporting: 

      - table
      - json
      - csv
      - count
      - yaml
      - total_bytes

which I assume was added after this ticket was created.

**Comment by swissspidy** [comment]
Marking this as a wontfix based on the discussion at #446
