### ISSUE TITLE
wp user create has a duplicate email argument

### ISSUE THREAD

**Issue by johnbillion** [wp-cli/entity-command#170]
`wp user create` has the following signature:

`wp user create <user-login> <user-email> [--role=<role>] [--user_pass=<password>] [--user_registered=<yyyy-mm-dd-hh-ii-ss>]
  [--display_name=<name>] [--user_nicename=<nice_name>] [--user_url=<url>] [--user_email=<email>] [--nickname=<nickname>]
  [--first_name=<first_name>] [--last_name=<last_name>] [--description=<description>] [--rich_editing=<rich_editing>] [--send-email]
  [--porcelain]`

Note that the email field appears once as the `<user-email>` positional argument, and once as the `--user_email` associative argument.

**Comment by danielbachhuber** [comment]
This was added in f1a0db06d1fe41121156e57e17010e19f8ab08cb
