### ISSUE TITLE
`wp post generate --post_content` hangs if there's no STDIN

### ISSUE THREAD

**Issue by johnbillion** [wp-cli/entity-command#175]
Running `wp post generate --prompt` will hang if the user enters `Y` for the `--post_content` parameter. I guess it's expecting input from stdin for this parameter.

**Comment by johnbillion** [comment]
Updated the issue title. This applies without the `--prompt` flag too. The command hangs if there's no stdin.

**Comment by schlessera** [comment]
The `-post_content` flag is documented as follows:
```
[--post_content]
    If set, the command reads the post_content from STDIN.
```

Although it is clear from that that WP-CLI will expect input from STDIN, I think the expected behavior would be to throw an error if no STDIN is provided, instead of hanging.

**Comment by schlessera** [comment]
This can be solved by checking whether we have STDIN input (through `WP_CLI\Entity\Utils::has_stdin()`) when the `--post_content` flag was passed and showing an error message if this is not the case.
