### ISSUE TITLE
--skip-email flag for wp user update

### ISSUE THREAD

**Issue by johnbillion** [wp-cli/entity-command#178]
The `wp user update <user> --user_pass=123` command will trigger an email sent by WordPress to notify the user that their password was updated.

It would be nice to have a `--skip-email` flag on this command to prevent that email from being sent out.

**Comment by schlessera** [comment]
There's already a WIP PR for that: https://github.com/wp-cli/entity-command/pull/155

**Comment by schlessera** [comment]
Closed via #155
