### ISSUE TITLE
Implement `--all` flag for `wp post term remove`

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/entity-command#18]
If you want to remove all terms of a given taxonomy from a post, it'd be nice to have an `--all` flag.

**Comment by Sidsector9** [comment]
@danielbachhuber Shouldn't the title be `wp post term remove` instead of `delete`?

**Comment by danielbachhuber** [comment]
@Sidsector9 You are correct.

**Comment by BhargavBhandari90** [comment]
@danielbachhuber if we need to add `--all`, then third parameter `term` should be optional associative argument like this `--term=cat1,cat2`.

So that we can add one more associative argument that is `--all`. 

Any other thought on this?

**Comment by danielbachhuber** [comment]
> if we need to add `--all`, then third parameter term should be optional associative argument like this `--term=cat1,cat2`.

You can make it an optional positional argument:

```
wp post term remove <id> <taxonomy> [<term>...] [--by=<field>] [--all]
```

If neither a term nor `--all` is provided, then the command should err similar to `wp plugin update`

```
$  wp plugin update
Error: Please specify one or more plugins, or use --all.
```

**Comment by BhargavBhandari90** [comment]
@danielbachhuber 

Thank you for the suggestion.

One more thing, after removing all terms from the post, the default term `uncategorized` should be assign to the post.

**Comment by danielbachhuber** [comment]
> One more thing, after removing all terms from the post, the default term `uncategorized` should be assign to the post

WordPress should handle this for you already.

**Comment by BhargavBhandari90** [comment]
> WordPress should handle this for you already.

Actually I used `wp_delete_object_term_relationships` for removing all terms. So it removes the default term too. So that we need to assign the default term.
