### ISSUE TITLE
Use get_object_taxonomies() for taxonomy list by post type object

### ISSUE THREAD

**Issue by grappler** [wp-cli/entity-command#181]
I was running the command from the example `wp taxonomy list --object_type=post --fields=name,public` and could not figure out why all of the taxonomies were not being displayed.

One of the taxonomies that was connected to the "post" object was also associated with other post types. Turns out this is one of the limitations([Core Trac](https://core.trac.wordpress.org/ticket/27918)) of `get_taxonomies()` which is used by [`wp taxonomy list`](https://github.com/wp-cli/entity-command/blob/master/src/Taxonomy_Command.php#L115).

A solution would be to use [`get_object_taxonomies()`](https://developer.wordpress.org/reference/functions/get_object_taxonomies/) instead.

I am not sure what the solution would be here. Perhaps add a different flag or add a new command.

**Comment by schlessera** [comment]
Changing this to use `get_object_taxonomies()` would be a breaking change, even if it would be a good one, so we have to consider the impact and the best course of action.

My general feel would be that the breaking change in this instance would not be a big issue, as I cannot think of a lot of use cases for actually scripting taxonomies and then failing over having more taxonomies than expected.

However, this might catch people by surprise that know of the Core behavior and expect WP-CLI to match that behavior.

I would be up to exploring adding a `--strict` filter, with `--strict` matching `get_taxonomies()` and `--no-strict` matching `get_object_taxonomies()`. I also think we could default to `--no-strict` without too many expected issues.
