### ISSUE TITLE
Define known allowed fields for `wp user (create|update)`

### ISSUE THREAD

**Issue by johnbillion** [wp-cli/entity-command#19]
`wp help user update` shows the following option in the help text:

```
--<field>=<value>
  One or more fields to update. For accepted fields, see wp_update_user().
```

The source for `wp_update_user()` in core does not actually list the accepted fields, but `wp_insert_user()` does.

Ideally the accepted fields would be listable in WP-CLI, but I appreciate this is a pain to maintain. Easy win is to change the suggested function in the help text to `wp_insert_user()`.

**Comment by danielbachhuber** [comment]
> Ideally the accepted fields would be listable in WP-CLI, but I appreciate this is a pain to maintain.

I'd actually be amenable to this now, because:

1. It's rare for `wp_insert_user()` to introduce new fields.
2. `wp_insert_user()` has a limited set of supported fields.
3. Listing the fields in the command docs also brings them into the terminal help docs.

Related #16, because I'm now contradicting myself.

**Comment by danielbachhuber** [comment]
For this issue, let's go ahead and define each of the known accepted fields for `wp user (create|update)`, e.g.:

```
--user_login=<login>
: A string that contains the user's username for logging in.
```

We'll want to keep `--<field>=<value>` to accept any additional arguments.

**Comment by danielbachhuber** [comment]
🔨

**Comment by emgk** [comment]
How can we test/run PR's code on the command line, As there is only one file which is wp-cli.phar which is can't be modified, So could you please tell me the exact way to test PR code in wp-cli terminal ?  @danielbachhuber

**Comment by danielbachhuber** [comment]
@emgk See https://make.wordpress.org/cli/handbook/pull-requests/
