### ISSUE TITLE
Getting option by ID

### ISSUE THREAD

**Issue by OksanaRomaniv** [wp-cli/entity-command#196]
Hello,

Is there a way to get option information by id? When you run wp db search for a string, it returns option table value with the key of the option id. But it there a way to get info about the option by this id? It's returning nothing when you run "wp option get {ID}" where ID is the option ID returned by wp db search.

Thanks!

**Comment by swissspidy** [comment]
There's no such way using the `wp option` set of commands. You could use the `wp db` command, but I don't recommend doing this.

WordPress options are essentially a key->value store. It's not advisable to look up options by their database IDs or to rely on these IDs in any other way as they might change. You can only rely on the key (= the option name).

`wp option get` just calls `get_option()` internally, which only accepts a key. If a site uses an object cache (Redis, Memcached, etc.), options will be stored in that object cache instead, and not the database. `get_option()` will then look for the options in the object cache. The database ID is useless in that case.
