### ISSUE TITLE
Setting option serialization issue 

### ISSUE THREAD

**Issue by ianwijma** [wp-cli/entity-command#197]
Hey WP CLI team!

First off, Thanks for creating an awesome interface to WordPress!

So I was playing around with WP CLI and when I was setting options in the form of objects I had some problems setting them in the database correctly.

So first a lil about the bug test environment: Its a clean install of WordPress, Installed using the following commands:
- `wp core download --path='/path/to/install/folder'`
- `wp config create --skip-check --path='/path/to/install/folder' --dbname='<dbname>' --dbuser='<user>' --dbhost='<host>' --dbpass='<pass>'`
- `wp core install --path='/path/to/install/folder' --url='<url>' --title='An amazing temporary blog!!!!!' --admin_name='admin' --admin_email='<email>' --admin_password='<pass>'`

Once done installing (I assume I didnt make any mistakes here) I started reproducing my bug where I tried 2 different, and logical way of the `option update` command:
- `wp option update test01 '{"enabled":"no"}'`
-- First try, Was hoping this was being serialized, But I was out of luck. This just put it as a string in the database
- `wp option update test02 'a:1:{s:7:"enabled";s:2:"no";}'`
-- Second try was also not a success, self serializing resulting in it being double serialized in the database: `s:29:"a:1:{s:7:"enabled";s:2:"no";}";`
- `wp option update test03 {"enabled":"no"}`
-- Now I tried it without the quotes around it, which also put it in the database without any quotes
- `wp option update test02 a:1:{s:7:"enabled";s:2:"no";}` 
-- This just resulted as expected into a syntax error from the CLI.

So my question is if I do anything wrong with setting the option? or did I bumped into a bug? because I see object used quite often in plugins like WooCommerce and WordPress self.

Here an image of the test results in the database.
![image](https://user-images.githubusercontent.com/17692119/43709929-7abde478-996e-11e8-9f58-6a589c4de680.png)

ps. Sorry if I missing some guild lines. First time making an issue for a WordPress/WP CLI related project.

**Comment by schlessera** [comment]
@ianwijma Your first approach works, but you need to add the `--format=json` flag.

**Comment by ianwijma** [comment]
Aahh, thanks! I missed that part! Thanks for the help!
