### ISSUE TITLE
WP Post List - Limit number of posts

### ISSUE THREAD

**Issue by theRKF** [wp-cli/entity-command#20]
We're running into some memory issues on a reasonably powerful dedicated server. The issue is that we're trying to run commands that apply to 10s or 100s of thousands posts.

Ex: `wp post delete $(wp post list --post_status=trash --format=ids)`
This crashes because the wp post list returns too many entries and PHP uses several GB of ram.

Sometimes we can get around this by using 
```
wp post list --post_status=trash --format=ids > posts.txt
wp post delete <posts.txt
```

However, sometimes even the wp post list command dies because of memory usage. If we could add a parameter to limit to X number of posts at a time this would be more manageable.

Thanks!

**Comment by danielbachhuber** [comment]
> If we could add a parameter to limit to X number of posts at a time this would be more manageable.

See `--posts_per_page=<count>`, `--paged=<page>` and other equivalent `WP_Query` arguments: https://codex.wordpress.org/Class_Reference/WP_Query
