### ISSUE TITLE
To make this repo easier to find, please put "comment" in the description

### ISSUE THREAD

**Issue by benlk** [wp-cli/entity-command#205]
This package provides the `comment` command, yet is named "entity-command". 

The description for this repo on Github is:

> Manage WordPress core entities.

When searching the wp-cli org for code or repositories related to comments, no results are found: https://github.com/wp-cli?utf8=%E2%9C%93&q=comment&type=&language=

Can you put the word "comment" somewhere in the repo's GitHub description?

An example of how this would work in search is searching the wp-cli org for "transient", which shows the cache-command repo because it has "transient" in its description. https://github.com/wp-cli?utf8=%E2%9C%93&q=transient&type=&language=

**Comment by wojsmol** [comment]
This can be added but even now this repo can be find - https://github.com/search?q=org%3Awp-cli+comment&type=Code. Put comment  in top search and select in this organization.

**Comment by benlk** [comment]
Yes, "comment" shows up in code searches, but it doesn't show up in *repository* searches. Someone who was searching using the front of the wp-cli org would not find the appropriate repo.

**Comment by chesio** [comment]
Same for the `option` command (and possibly others in this repo). When I had to update my `composer.json` after WP-CLI 2.0 has been released, it took me a while to find what package (repository) implements the `option` command...
