### ISSUE TITLE
Site List returns multiple sites when --url is set

### ISSUE THREAD

**Issue by musicaljoeker** [wp-cli/entity-command#218]
Hi there,

I am trying to extract a `blog_id` for a specified site in our multisite environment. For every other wp cli command I've used, this a site is targeted via the global --url parameter, which leads me to construct this command: `wp site list --url=mydomain.com/this-is-the-site-i-want --field=blog_id`. However when I run this, I always get every site's `blog_id` in our multisite environment. Am I using `site list` command wrong, or is this a bug in the wp cli?

Thanks!

**Comment by schlessera** [comment]
As stated in the docs for `wp site list`:
```
site list - Lists all sites in a multisite installation.
```

If you want to display the `blog_id` of the subsite you're currently targeting, you can do something like this:

```
wp eval --url=mydomain.com/this-is-the-site-i-want 'echo get_current_blog_id();'
```

GitHub issues are meant for enhancement requests and specific, reproducible bugs, not for general support questions. Therefore I close this issue now.

If you still have questions, the easiest way to get support is to join us in the #cli channel on the [Make WordPress Slack Team](https://make.wordpress.org/chat/).

**Comment by musicaljoeker** [comment]
I appreciate the help! Sorry thought this might've been a reproducible bug since the --url selector normally filters on sites within the multisite. Cheers.
