### ISSUE TITLE
Allow deleting multiple options at once

### ISSUE THREAD

**Issue by swissspidy** [wp-cli/entity-command#220]
Originally reported in https://github.com/wp-cli/wp-cli/issues/2972.

Right now it's possible to delete multiple posts, comments, terms, etc. at once but not options.

For consistency reasons we should consider supporting `wp option delete <key>...` as well.

**Comment by BrianHenryIE** [comment]
Did #247 close this?

I'd like wildcard support. (I know I can execute SQL anyway.)

`wp option delete bh_optionname_%`

or similar syntax. `*` would be nice, regex would be good, SQL seems appropriate, but I don't know WP CLI enough to know what  is most consistent with its existing design.

My exact use case is that I wrote a plugin early this year that used options to tracking completion of tasks, but I didn't properly clean up. I now see the mess I've left and CLI seems the most appropriate way to clean up.

**Comment by schlessera** [comment]
Yes, indeed, #247 closed this.

@BrianHenryIE can you copy the above comment into a new issue, please?
