### ISSUE TITLE
Get post by slug

### ISSUE THREAD

**Issue by Mte90** [wp-cli/entity-command#226]
Looking on https://developer.wordpress.org/cli/commands/post/get/ it is possible to get a post only by ID but not by the slug or the url.
On WordPress it is possible to get the id/post object with https://codex.wordpress.org/Function_Reference/get_page_by_path
so I think that is possible to integrate other ways to interface to the entity command.
Our user case:

* List of URLs extrapolated from Google Search console
* Elaborate them based on our needs
* Delete them by wp cli commands https://developer.wordpress.org/cli/commands/post/delete/

I was thinking to do a plugin for that but I don't know how to extend the `get` command.

**Comment by Mte90** [comment]
FIrst prototype that works and letting me to keep working but of course is not the best implementation https://github.com/CodeAtCode/wp-cli-getbyurl

**Comment by hypgfrch** [comment]
Makes me wonder to see this wonderful 'WP_CLI' great iniciative, just to see it failing at this very basic step. 
We will be aware of this tool progress with great interest.

**Comment by Mte90** [comment]
Ehi @tomjn this method works with posts but mine at https://github.com/CodeAtCode/wp-cli-getbyurl detect also taxonomies and multiple post types :-)

**Comment by skorasaurus** [comment]
I've been really interested in seeing this happen; the most common use case that I run is hearing from marketing or another co-worker there's a small misspelling or the wrong class name was used on an element; and need to go in there and fix it. 

Ideally, I'd like to edit a post by knowing a slug; 

If it helps, I've crafted the following query that I use to get a post by a slug: 

1. `wp post list --post_type=any --post__in=$(wp db query 'SELECT ID FROM wp_dtex_posts WHERE post_title LIKE "%martin%" AND post_status="publish"' --skip-column-names |  paste -s -d ',' - )`
(in step 1, swap out martin with the slug; or if you don't know the entire slug; insert the portion of it)
The output includes the ID, post_title, post_name (aka: slug), date, and the status.

**Comment by Mte90** [comment]
By wpcli package implement this command that can put in pipe or used in script to get the id by a slug, in the meantime that the project implement something similar or better :-)

**Comment by Sidsector9** [comment]
Adding to this, WP-CLI command are composable. You can use `wp post get` to get a post by slug.
You can use the following:

`wp post get $(wp post list --field="ID"  --name="POST_SLUG")`

I'm closing the issue as resolved. Please feel free to reopen if needed.
