### ISSUE TITLE
Add activation status to 'site list' command

### ISSUE THREAD

**Issue by milosa** [wp-cli/entity-command#228]
It would be useful to have an option to get the activation status of a site in a multipage installation.
By activation, I mean the status you control with: `wp site activate 2` or `wp site deactivate 2`

Something like: `wp site list --field=activated` which would return true or false.

Is this already possible? Or have I overlooked something? If not, I will look into making a PR for this.

**Comment by schlessera** [comment]
@milosa, this can already be provided, but the internal field is called `deleted`, not `activated`.

So, you can see the information you need with the following command:

```
$ wp site list field=deleted
```

It will return `0` for active sites, and `1` for inactive (= deleted) sites.
