### ISSUE TITLE
Purge option from alloptions

### ISSUE THREAD

**Issue by crstauf** [wp-cli/entity-command#229]
If an option is marked as `autoload`, its added to the `alloptions` key of the `options` group. This means that in order to purge the value there and have the value update from the database, the entire key `alloptions` has to be purged.

I'm not sure what the solution looks like, but I've run into this several times; being able to purge a single, autoloaded option from the cache would be excellent.

**Comment by schlessera** [comment]
@crstauf If you're using the WordPress methods to change an option, it will be refreshed in the cache automatically. Can you explain a bit more what specific use case you are trying to solve?

**Comment by crstauf** [comment]
@schlessera Occasionally I change an option's value directly through the database; in that event, I need to also purge the cached value from the object cache. If the option is autoloaded, the only way to purge the value is to purge the entire `alloptions` key, which I'd rather not do.

The ability to purge or set an item within `alloptions` would alleviate the issue.

**Comment by crstauf** [comment]
@schlessera I will acknowledge that it never occurred to me to use `wp option update` though.

**Comment by schlessera** [comment]
> I will acknowledge that it never occurred to me to use wp option update though.

I assume this will solve your specific use case then?

**Comment by crstauf** [comment]
@schlessera I assume so, yes.
