### ISSUE TITLE
wp site create throws a warning after upgrade to WP 5.1

### ISSUE THREAD

**Issue by fakekamrankhan** [wp-cli/entity-command#239]
After upgrading to WP 5.1, the wp cli is throwing a warning when we try to create a new site on the network using `wp site create`:

> `Notice: wpmu_new_blog is <strong>deprecated</strong> since version 5.1.0! Use wp_insert_site instead. in /var/www/html/wp-includes/functions.php on line 4605`

Is there going to be a fix for this anytime soon?

**Comment by danielbachhuber** [comment]
> Is there going to be a fix for this anytime soon?

If you'd like to submit a pull request with the fix, we can look at incorporating it into the next release. I believe 2.2.0 will come around April.

**Comment by musicaljoeker** [comment]
Hello @fakekamrankhan and @danielbachhuber. I would be happy to help figure this issue out and submit a pull request should a code change be necessary. I am new to contributing to the WP-CLI, so please forgive me if I ask silly questions or if I miss something obvious.

Running the `wp site create` command did not throw any errors for me. I noticed that on line 398 of the `Site_Command.php` file, it listed:
```{php}
$id = wpmu_create_blog( $newdomain, $path, $title, $user_id, array( 'public' => $public ), $network->id );
```
which is the same function (wpmu_create_blog) that is used in native WordPress to create new multi-sites (line 138 of `site-new.php` file).

@fakekamrankhan could this error be throwing in some other place in your code base or perhaps could you please give more details to reproduce this issue? Thanks!

**Comment by schlessera** [comment]
@musicaljoeker Did you use `wp site create` to add a new site to an existing multisite network? The issue does not relate to single site creation.

**Comment by musicaljoeker** [comment]
Hi @schlessera, yes that is what I did. I set up a new multisite network (with one site), ran `wp site create --slug=test` with no errors. I ran the command again to test with multiple sites in the network `wp site create --slug=test2` with no errors.

**Comment by fakekamrankhan** [comment]
Sorry, this issue can now be closed. We found that the error was not with wp cli but a third-party plugin ([Yoast SEO](https://github.com/Yoast/wordpress-seo/issues/12292)) still using the `wpmu_new_blog` hook that has been deprecated since 5.1.

**Comment by Sidsector9** [comment]
Closing the issue as per comment https://github.com/wp-cli/entity-command/issues/239#issuecomment-480106640
