### ISSUE TITLE
List posts with categories

### ISSUE THREAD

**Issue by dinotal** [wp-cli/entity-command#243]
Is it possible to list posts with the corresponding categories using wp-cli, similar to what is discussed here regarding listing posts with meta_key and meta_value?
https://github.com/wp-cli/entity-command/issues/26 

What I'm looking for is listing all posts with meta values and categories.

**Comment by szepeviktor** [comment]
@dinotal You could reuse WP-CLI's output like this

```bash
for POST in $(wp post list --field=ID); do echo -n "${POST}:"; wp post term list "$POST" category --field=slug | paste -s -d","; done
```

**Comment by schlessera** [comment]
@dinotal This is already possible by using one of the category filters that `WP_Query` provides: https://codex.wordpress.org/Class_Reference/WP_Query#Category_Parameters

As an example, here is the command to list all posts that are either in category `alpha` or in category `beta`:
```
wp post list --category_name=alpha,beta
```

**Comment by joeldcanfield** [comment]
Clarifying the answers: the question was not "how to list posts in certain categories" but "how to include categories when listing posts."

@szepeviktor's solution works as expected.
