### ISSUE TITLE
Empty Warnings 

### ISSUE THREAD

**Issue by Forz70043** [wp-cli/entity-command#255]
Update author email comment:
`wp comment update ID_COMMENT set --comment_author_email "XXX@email-address.com" --allow-root`.

Output
Success: Updated comment ID_COMMENT.
Warning:
Warning: 
-------------------------------
WP-CLI version:	2.2.0

In Warning is missing something ?

**Comment by thrijith** [comment]
@Forz70043 I think the correct command would be 

`wp comment update ID_COMMENT --comment_author_email="XXX@email-address.com" --allow-root`

Please refer https://developer.wordpress.org/cli/commands/comment/update/ for valid args and options.
