### ISSUE TITLE
wp user reset-password always shows Success

### ISSUE THREAD

**Issue by johnbillion** [wp-cli/entity-command#258]
## Bug Report

- [X] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [X] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

**Describe the current, buggy behavior**

The `wp user reset-password` always shows a `Success` message, even when provided with an invalid user name.

**Describe how other contributors can replicate this bug**

- Run `wp user reset-password invalid-user-name`
- Observe that a `Warning` message is shown about the invalid user name
- Observe that the `Success` message is still shown and the exit code is `0`

**Describe what you would expect as the correct outcome**

I would expect this command to exit with `1` and to display an appropriate error message.

**Comment by schlessera** [comment]
I agree, there's no point in continuing without a valid user, so the warning should actually be an error.

**Comment by schlessera** [comment]
Fixed via #271
