### ISSUE TITLE
Improve the grammar of wp comment spam output

### ISSUE THREAD

**Issue by johnbillion** [wp-cli/entity-command#259]
## Bug Report

- [X] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [X] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

**Describe the current, buggy behavior**

When running `wp comment spam <id>`, the text in the output doesn't use good grammar.

**Describe how other contributors can replicate this bug**

- Run `wp comment spam <id>` with an ID of an existing comment
- Observe the output: `Success: Marked as spam comment <id>.`

**Describe what you would expect as the correct outcome**

Ideally the output would say `Success: Marked comment <id> as spam.`

**Comment by marty-crane** [comment]
I'll take a look

**Comment by marty-crane** [comment]
https://github.com/wp-cli/entity-command/pull/272
