### ISSUE TITLE
List posts with a certain meta

### ISSUE THREAD

**Issue by szepeviktor** [wp-cli/entity-command#26]
Could we have a `wp post list` option that checks for a certain meta? (existence/value)

**Comment by danielbachhuber** [comment]
Could you describe the use case in greater detail? Is this currently possible using `WP_Query` arguments?

**Comment by szepeviktor** [comment]
Yes. Invalid issue :(

`wp post list --post_type=product --meta_key=_extra_cost_enable --meta_value=yes`

**Comment by szepeviktor** [comment]
Even highly complicated ones are possible:

```bash
$ for POST in $(wp post list --post_type=product --meta_key=_extra_cost_enable --meta_value=yes --format=ids); do wp post get $POST --field=post_title;
wp post meta list $POST --keys=_extra_cost_enable,_extra_cost_enable_qty,_extra_cost_label,_extra_cost_amount,_extra_cost_amount_quatity; done
```
