### ISSUE TITLE
Add support for targeting meta ids

### ISSUE THREAD

**Issue by tecking** [wp-cli/entity-command#264]
## Feature Request

I hope there is a new `wp meta` that can handle metadata directly with meta ids as arguments. or additional `wp post meta` parameters.
Currently, attempting to use postmeta with meta id as an argument is verbose. 
For example `wp eval 'update_metadata_by_mid( "post", <meta_id>, <meta_value> );'`

**Comment by danielbachhuber** [comment]
Thanks for the suggestion, @tecking.

Given how infrequently this should be needed, I think your proposed workaround is sufficient.
