### ISSUE TITLE
wp user create ignores --nickname

### ISSUE THREAD

**Issue by Hlsgs** [wp-cli/entity-command#274]
`wp user create` ignores `--nickname` and always uses  the username instead

**Comment by johnbillion** [comment]
It looks like this affects other fields too, such as `--user_nicename` and `--user_url`. See #301 .

**Comment by schlessera** [comment]
Weirdly enough, the `nickname` is only available when you retrieve users via `get_users()`, and not when you retrieve them via `get_user_by()`... See https://github.com/wp-cli/wp-cli/pull/5600

**Comment by Hlsgs** [comment]
Confirming still present in wp cli v2.6.0

**Comment by schlessera** [comment]
@Hlsgs Yes, indeed. I did some work in solving this, but it turns around it is mostly a bug in `get_users()`. I then tried to use `WP_User_Query` across the board for all WP-CLI user queries, but that just turned up with different bugs of its own.
This needs more careful investigation in how best to solve.

**Comment by Hlsgs** [comment]
> @Hlsgs Yes, indeed. I did some work in solving this, but it turns around it is mostly a bug in `get_users()`. I then tried to use `WP_User_Query` across the board for all WP-CLI user queries, but that just turned up with different bugs of its own. This needs more careful investigation in how best to solve.

Got it! Thank you for the lowdown.
