### ISSUE TITLE
Get list of users for specific site on WP Multisite

### ISSUE THREAD

**Issue by Feriman22** [wp-cli/entity-command#277]
I would like to list users of specific site. I'm using WordPress Multisite.

Is it possible? I didn't see any option [here](https://developer.wordpress.org/cli/commands/user/list/) for do this.

Thanks!

**Comment by Sidsector9** [comment]
You can use the `--url` [global parameter](https://developer.wordpress.org/cli/commands/user/list/#global-parameters)

For example:
`wp user list --url=site1.example.com`

I'm marking this as resolved for now. Feel free to reopen if you're facing issues with this command.
