### ISSUE TITLE
add new text without opening vim, like **echo TEXT > POST_ID**

### ISSUE THREAD

**Issue by kirgizmustafa17** [wp-cli/entity-command#281]
Are there any way to do this?
I will update my post sometimes and a script will do this, so how can I do this with vim editor or without vim editor?

**Comment by schlessera** [comment]
@kirgizmustafa17 You can use `wp post update <POST_ID> --post_content=<TEXT>` for this.

Please note that GitHub issues are meant for enhancement requests and specific, reproducible bugs, not for general support questions. For support options, please review http://wp-cli.org/#support

The easiest way to get support is to join us in the #cli channel on the [Make WordPress Slack Team](https://make.wordpress.org/chat/).
