### ISSUE TITLE
Add --all argument to reset-password command

### ISSUE THREAD

**Issue by derweili** [wp-cli/entity-command#282]
## Feature Request
According to https://github.com/wp-cli/entity-command/issues/249#issuecomment-485042257 the `wp user reset-password` command ist intended to reset, the user's password (e.g. to handle a password breach)

In this scenario it is required to reset all passwords for all users. Therefore I would expect the command to have an `--all` argument which gives the user the possibility to reset all passwords of all users at once.

Of cause this is possible to combine the `wp user list` with the `wp user reset-password` command achieve the same result. But since many other commands have an `--all` argument I would expect to have it available for the `wp user reset-password` command, too.

**Comment by cristian-rossi** [comment]
A --role argument would be nice too.

**Comment by JiveDig** [comment]
+1. For now I do it by role, via: 
```
wp user reset-password $(wp user list --fields=ID --role=administrator)
```

Do you know how to do this for all roles via `wp user list`?
