### ISSUE TITLE
Please document how to set arrays with wp post meta add

### ISSUE THREAD

**Issue by benlk** [wp-cli/entity-command#308]
## Feature Request

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).

**Describe your use case and the problem you are facing**

I have a post meta field that contains an array of integers:

```
$ wp post meta get 18669574 related_links
array (
  0 => 18638855,
  1 => 18500538,
  2 => 18500512,
)

```

If I view that post meta with `wp post meta list`, what I get in response is instead a serialized array:

```
$ wp post meta list 18669574
+----------+-------------------------------------------+-------------------------------------------
| post_id  | meta_key                                  | meta_value                                
+----------+-------------------------------------------+-------------------------------------------
| 18669574 | related_links                             | a:3:{i:0;i:18638855;i:1;i:18500538;i:2;i: |
|          |                                           | 18500512;}                                |
```

I'd like to add similar post meta to another post. I would expect that `wp post meta add 19031933 related_links 'a:1:{i:0;i:19031878;}'` would add post meta as an array to post 19031933, but instead what happens is:

```
$ wp post meta list 19031933 
+----------+---------------+-------------------------------+
| post_id  | meta_key      | meta_value                    |
+----------+---------------+-------------------------------+
| 19031933 | related_links | s:21:"a:1:{i:0;i:19031878;}"; |
+----------+---------------+-------------------------------+
```

**Describe the solution you'd like**

If it is possible to set an array-type post meta key from the command line, I'd like for there to be documentation at https://developer.wordpress.org/cli/commands/post/meta/add/ describing how to do so.

If it's not possible, I'd like for there to be a list of types of post meta which can't be created with `wp post meta add`, and suggested alternatives for setting them.

**Comment by milindks** [comment]
here is an example to update post meta using wp cli command 

`wp post meta update 19031933 related_links  '{"0":"18638855","1":"18500538","2":"18500512"}' --format=json`

Let me know if this helps you

**Comment by milindks** [comment]
also, `wp post meta update` works similar to `wp post meta add` if they target meta key is not present.

**Comment by benlk** [comment]
Thank you for the effort in putting this together. Unfortunately, I no longer recall which project I was working on that required this, so I don't have an env set up to test your solution.

If some future reader comes across this issue and tests the solution, please post your results.

**Comment by cbk882** [comment]
Hi there, seems to be me, the "future reader" :-)
Works like a charm.
`wp post meta add 114948 location '{"address":"Street No. 12, 12345 Berlin","lat":"1.0000","lng":"2.0000"}' --format=json`
does the trick, I searched for the last half hour. Would be great if this or any similar example would find the way into the documentation.

**Comment by Sidsector9** [comment]
This is already documented. Arrays can be set by first converting it to JSON format and then using `--format=json`

In your example:

`wp post meta add 19031933 related_links 'a:1:{i:0;i:19031878;}'`

the value is serialized and not json.

`wp add post meta` serializes the value that is passed to it. When you pass data that is already serialized, the command `wp add post meta` will serialize it again.

To set an array as a meta value, it should be in JSON format.

For example, if you want to set a meta key `user_details` as the array:

```php
array(
  'name' => 'John Doe',
  'age => 35,
);
```

The command will be:

`wp post meta add 1 user_details --format=json '{"name":"John Doe","age":35}'`

I'm closing this as resolved.

**Comment by benlk** [comment]
Can that be added as an example to https://developer.wordpress.org/cli/commands/post/meta/add/ ?

**Comment by cbk882** [comment]
> Can that be added as an example to https://developer.wordpress.org/cli/commands/post/meta/add/ ?

That would be a great idea for all guys like me, who read the documentation of the commands, they want to use, and don't read all of the documentation :-)
