### ISSUE TITLE
Cannot revoke super admin for non-existent user

### ISSUE THREAD

**Issue by johnbillion** [wp-cli/entity-command#31]
Given a value for the `site_admins` site meta field which contains a username of a non-existent user, it's not possible to revoke this ghost super admin via WP-CLI.

The `wp super-admin remove` warns that the username you're attempting to revoke super admin access for is invalid, but then subsequently presents an incorrect success message:

```shell
$ wp super-admin remove admin
Warning: Invalid user ID, email or login: 'admin'
Success: Revoked super-admin capabilities.
```

In fact, the super-admin caps have not been revoked from the ghost admin user.

**Comment by johnbillion** [comment]
Whoops, wrong repo.

**Comment by danielbachhuber** [comment]
Thanks for the report, @johnbillion. I've moved it over to the correct repo https://github.com/wp-cli/super-admin-command/issues/5
