### ISSUE TITLE
Command wp option patch update MyKey 'MyKeyPath' 'MyNewValue' hangs on Windows but works on Linux

### ISSUE THREAD

**Issue by JohnEricson** [wp-cli/entity-command#311]
## Bug Report

**Describe the current, buggy behavior**

Updating values on an existing key in a hash array of string => string doesn't work on Windows while it works fine on Linux. On Windows it hangs while on Linux it reports `Success: Updated '_site_transient_theme_roots' option.`.

The command that is failing is: `./wp option patch update _site_transient_theme_roots 'twentynineteen' 'NEWvalue'`
On Windows wp-cli freezes and I have to kill it with Ctrl+C, while on Linux it works fine.

The ` _site_transient_theme_roots` key is an example to easily reproduce the problem. It's created by the `bbpress` plugin I installed like this: `./wp plugin install bbpress --activate`.

We have WordPress websites installed on both Linux and Windows servers and we try to find a consistent way to configure settings in the wp_options table. The wp_option we need to configure looks like this:

> ./wp option get _site_transient_theme_roots
> array (
> 'twentynineteen' => '/themes',
> 'twentytwenty' => '/themes',
> 'twentytwentyone' => '/themes',
> )

And in json-format like this:

> ./wp option get _site_transient_theme_roots --format=json
> {"twentynineteen":"\/themes","twentytwenty":"\/themes","twentytwentyone":"\/themes"}

**Describe how other contributors can replicate this bug**

Install a clean installation of WordPress like this:

***Windows***
1. choco install php --version=7.4.16
2. choco install apache-httpd mysql openssl
3.  Restart OS to ensure PATH is updated.
4. Edit php.ini add add extensions for openssl and mysql.
5. ./wp core download
6. Create mysql user.
7. ./wp config create --dbname=wp --dbuser=wp --dbpass=securepswd
8. ./wp db create
9. ./wp core install --url=example.com --title=Example --admin_user=supervisor --admin_password=strongpassword --admin_email=info@example.com
10. ./wp plugin install bbpress --activate

11. Look at the default value for the key `_site_transient_theme_roots`:
./wp option get _site_transient_theme_roots
array (
  'twentynineteen' => '/themes',
  'twentytwenty' => '/themes',
  'twentytwentyone' => '/themes',
)

12. ./wp option patch update _site_transient_theme_roots 'twentynineteen' 'NEWvalue'

Now it hangs on Windows, while the same command works fine on Linux 🙁

**Describe what you would expect as the correct outcome**

I expect it to work the same as on Linux. Like this that happens on Linux:
```
./wp option patch update _site_transient_theme_roots 'twentynineteen' 'NEWvalue'
Success: Updated '_site_transient_theme_roots' option.
```

**Let us know what environment you are running this on**

***Windows***
```
PS C:\wp-cli> ./wp cli info
OS:     Windows NT 10.0 build 14393 (Windows Server 2016) AMD64
Shell:  C:\Windows\system32\cmd.exe
PHP binary:     C:\tools\php74\php.exe
PHP version:    7.4.16
php.ini used:   C:\tools\php74\php.ini
WP-CLI root dir:        phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:      phar://wp-cli.phar/vendor
WP_CLI phar path:       C:\wp-cli
WP-CLI packages dir:
WP-CLI global config:
WP-CLI project config:  C:\wp-cli\wp-cli.yml
WP-CLI version: 2.4.0
```

***Linux***
```
vagrant@app:~/wp-cli$ ./wp cli info
OS: Linux 4.15.0-136-generic #140-Ubuntu SMP Thu Jan 28 05:20:47 UTC 2021 x86_64
Shell: /bin/bash
PHP binary: /usr/bin/php7.2
PHP version: 7.2.24-0ubuntu0.18.04.7
php.ini used: /etc/php/7.2/cli/php.ini
WP-CLI root dir: phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir: phar://wp-cli.phar/vendor
WP_CLI phar path: /home/vagrant/wp-cli
WP-CLI packages dir:
WP-CLI global config:
WP-CLI project config: /home/vagrant/wp-cli/wp-cli.yml
WP-CLI version: 2.4.0
```

**Provide a possible solution**

**Provide additional context/Screenshots**

**Comment by danielbachhuber** [comment]
Hey there... if you're still having trouble, feel free to stop by the `#cli` channel on [WordPress.org Slack](https://make.wordpress.org/chat/) if you'd like help debugging further.
