### ISSUE TITLE
Add site ID argument to "site empty" command

### ISSUE THREAD

**Issue by Luc45** [wp-cli/entity-command#313]
## Feature Request

- [X] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).

**Describe your use case and the problem you are facing**

The command `wp site empty` does not accept a site ID argument like `wp site delete 123`, therefore, even though it belongs to the `site` command, that deals with multi-sites, it only has effect on the main site of the network.

I have tried `wp site empty --url=http://foo.bar/some-ms-instance` as well, but it ignores `some-ms-instance` and asks if I want to empty `http://foo.bar` instead:

```
➜  1617809280 wp site empty --url=http://na-evolve.loc/1617809280/some-subsite/
Are you sure you want to empty the site at 'http://na-evolve.loc/1617809280' of all posts, comments, and terms? [y/n] ^C
```

The `empty` function: https://github.com/wp-cli/entity-command/blob/master/src/Site_Command.php#L250

Essentially, it seems I'd need WP_CLI to execute `switch_to_blog(123)` before running the command.

**Comment by danielbachhuber** [comment]
Thanks for the suggestion, @Luc45 !

I don't think we'll make this change at this time. `wp site empty` is _performing an operation on the site_, while `wp site delete` is directly manipulating the object.
