### ISSUE TITLE
Allow changing a user's login

### ISSUE THREAD

**Issue by johnbillion** [wp-cli/entity-command#32]
Within wp-admin, users are prevented from changing the `user_login` field for any user. There's no reason this same restriction should be in place in WP-CLI, but it is.

Culprit: https://github.com/wp-cli/entity-command/blob/66f3a19272492e87ec23be730c02918e96e70cb3/src/User_Command.php#L427-L430

Granted, there are side effects to changing the `user_login` field, such as a mismatch between the `user_nicename` field, but this could be communicated as part of the command feedback.

Related core ticket: https://core.trac.wordpress.org/ticket/39123

**Comment by danielbachhuber** [comment]
> There's no reason this same restriction should be in place in WP-CLI, but it is.

There is a reason: generally, WP-CLI is expected to operate in a similar manner to the WordPress admin. There are obvious workarounds (e.g. using `wp db query` to instead run a MySQL update command) but the explicit interface of WP-CLI is meant to emulate the web interface where appropriate.

If the WordPress admin changes its behavior, then we can change the behavior in WP-CLI too.
