### ISSUE TITLE
session tokens not always shown

### ISSUE THREAD

**Issue by DanielRuf** [wp-cli/entity-command#323]
## Bug Report

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [x] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

**Describe the current, buggy behavior**

A clear and concise description of the behavior that produces a wrong result or error.

Remember to provide some context to make sure we're all on the same page when reasoning about this.

**Describe how other contributors can replicate this bug**

- run `php ../wp-cli.phar user session list 1`
- run `php ../wp-cli.phar db query 'SELECT * FROM wp_usermeta where meta_value LIKE "%1a.b.c.d%"'`

**Describe what you would expect as the correct outcome**

The `user session list 1` command should show the session_token entries, like the `db query` one does. There seems to be some issue, at least the command does not output any sessions, even if there are session_tokens entries.

**Let us know what environment you are running this on**

```
OS:	Linux 4.19.0-17-amd64 #1 SMP Debian 4.19.194-1 (2021-06-10) x86_64
Shell:	/bin/bash
PHP binary:	/usr/bin/php74.wrp.cli
PHP version:	7.4.20
php.ini used:	/home/httpd/php74-ini/xxxx/php.ini
MySQL binary:	/usr/bin/mysql
MySQL version:	mysql  Ver 14.14 Distrib 5.7.34, for Linux (x86_64) using  EditLine wrapper
SQL modes:	
WP-CLI root dir:	phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:	phar://wp-cli.phar/vendor
WP_CLI phar path:	/usr/www/users/xxx/redacted
WP-CLI packages dir:	/usr/home/xxx/.wp-cli/packages/
WP-CLI global config:	
WP-CLI project config:	
WP-CLI version:	2.5.0
```

**Provide additional context/Screenshots**

<img width="548" alt="Bildschirmfoto 2021-07-05 um 21 30 14" src="https://user-images.githubusercontent.com/827205/124512334-61e4ef80-ddd8-11eb-94ae-e87f84998a7e.png">

<img width="1085" alt="Bildschirmfoto 2021-07-05 um 21 13 46" src="https://user-images.githubusercontent.com/827205/124512336-627d8600-ddd8-11eb-8f88-e2f244a15d31.png">

**Comment by danielbachhuber** [comment]
Thanks for the report, @DanielRuf !

Were you able to track the problem down further?

**Comment by DanielRuf** [comment]
Oh ok, so you close issues when there is no response after a while? Sorry, had other more important things to do.

Can you reproduce it locally?

**Comment by DanielRuf** [comment]
Hm, weird. The database in my case contained more than the command returned.

Unfortunately I can not provide more details since this was the result during an analysis of a compromised website and we don't keep logs or data of customers for good reasons.

**Comment by danielbachhuber** [comment]
> Unfortunately I can not provide more details since this was the result during an analysis of a compromised website and we don't keep logs or data of customers for good reasons.

@DanielRuf Makes sense! It seems like it might've been specific to that environment.

If you run into it in the future, it'd be great to see if it can be reproduced in a generic WordPress environment. Feel free to pop into the `#cli` channel on [WordPress.org Slack](https://make.wordpress.org/chat/), and someone might be able to help you debug.
