### ISSUE TITLE
How the content of a page is copied to others pages by wp cli ?

### ISSUE THREAD

**Issue by scoopsat** [wp-cli/entity-command#328]
**Hello,

I have multiple pages on my wordpress website.
For example, I have pages with the following ID's:  10, 20, 30, 40,

The page with content is holding id=10

I want to copy the same content of the page id=10 to the rest of the pages.

What is the command used in wp cli?**

**I used the following command, nothing changed:

wp post update 20 --status=Publish --from-post=10

Thank you**

**Comment by Sidsector9** [comment]
Hi @scoopsat , [WP-CLI commands are composable](https://make.wordpress.org/cli/handbook/contributions/philosophy/#composability-is-always-a-good-idea):

`wp post update 20 30 40 --post_content="$(wp post get 10 --field=content)"`

I'm closing this as resolved. Please feel free to reopen if this did not work for you.
