### ISSUE TITLE
New command `wp (api|json) generate application-password`

### ISSUE THREAD

**Issue by pfefferle** [wp-cli/entity-command#329]
## Feature Request

- [X] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).

**Describe your use case and the problem you are facing**

A new cli command to handle API commands in general and a command to generate `application-passwords` in particular.

**Describe the solution you'd like**

To setup a WordPress blog using the CLI, it would be helpful to also have a command to pre-generate `application-passwords`.

**Comment by swissspidy** [comment]
Yeah that is a good question... Core never really adds new tables and perhaps user meta was considered to be a good fit because of the number of expected entries. I'd have to dig up the core trac ticket to get the context though.
