### ISSUE TITLE
Allow filtering user list by users with no role

### ISSUE THREAD

**Issue by johnbillion** [wp-cli/entity-command#34]
The `wp user list` command accepts a `--role` filter, but this does not support users with no role.

In wp-admin, the Users screen now supports filtering by users with no role. It uses `none` as the role name.

Bear in mind there is a bug in core at the moment which prevents such users from appearing when multisite is enabled. Might want to wait until this is fixed: https://core.trac.wordpress.org/ticket/36196

**Comment by johnbillion** [comment]
The core bug is now fixed in trunk, scheduled for 4.9.

**Comment by danielbachhuber** [comment]
@johnbillion Based on the commit, it seems like WP-CLI is unaffected and could implement this enhancement without WP 4.9 as a requirement. Is my assessment correct?

> It uses none as the `role` name.

To clarify, the WP-CLI implementation would be `wp user list --role=none` ?

**Comment by johnbillion** [comment]
I'll take a look.

**Comment by danielbachhuber** [comment]
@johnbillion Can you write a simple Behat test to describe how you'd like this to behave?

**Comment by BhargavBhandari90** [comment]
I think for this, we need to allow user adding without role using `wp user create`?

OR we are just looking for getting users with no role?

Currently adding PR for getting users with no role only.

**Comment by danielbachhuber** [comment]
> I think for this, we need to allow user adding without role using `wp user create`?
> 
> OR we are just looking for getting users with no role?

Just the latter at the moment — users with no role.
