### ISSUE TITLE
When entering only a string of numbers or an int in the post name, wp cli adds "-2" at the end

### ISSUE THREAD

**Issue by dcivera** [wp-cli/entity-command#340]
When using wp post create or update with --post_name and a string only made of numbers or an int (e.g. --post_name='211221' or --post_name=211221), a "-2" is automatically added to the end of the name and it can't be removed, even manually using the WP interface. However, if I create the post within WP's interface, I can just use numbers.

**Comment by Sidsector9** [comment]
Hi @dcivera, this is the intended behavior from WordPress. A number-only slug can cause conflict with the date archive and for that reason a `-2` is appended.
