### ISSUE TITLE
"user reset-password" doesn't display the new randomly-generated password, suggest adding a switch to enable

### ISSUE THREAD

**Issue by dsXLII** [wp-cli/entity-command#342]
## Feature Request

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).

**Describe your use case and the problem you are facing**

`wp user reset-password username` does not display the new password. 

As a comparison/example: when you create a new user with the CLI, and don't specify a password, the new randomly-generated password is displayed. Admittedly this is a different use case, in that you only create one account at a time with `wp user create` but you can reset multiple users' passwords.

**Describe the solution you'd like**

When resetting the password of a single user, I would like the option of having the password displayed. Something like `wp user reset-password foo --show-password` or similar.

This probably should NOT be done by default, because that would be a change to existing behavior, and if users are currently doing password resets in an automated fashion could lead to passwords being logged in places where they weren't before and thus comes as a surprise. And I'm not sure it makes sense to do so when multiple users are specified on the command line. (Or at least that's a bit more of a refactor than adding a switch, as you'd then have to handle fields and otherwise do a proper "generate output" routine.)

**Comment by danielbachhuber** [comment]
I'm open to a `--show-password` flag if someone wants to put together a pull request for it.

**Comment by dsXLII** [comment]
Completely forgot about this, this was one whole job ago. :) 

Anyway, https://github.com/wp-cli/entity-command/pull/394 .

**Comment by dsXLII** [comment]
And a possible opportunity for improvement: When you create a new user, we call `wp_generate_password(24)` but here we only call `wp_generate_password()` which defaults to a 12-character password. Any specific reason for the discrepancy?

**Comment by danielbachhuber** [comment]
🚢
