### ISSUE TITLE
`wp post list` returns json without proper encoding

### ISSUE THREAD

**Issue by kanlukasz** [wp-cli/entity-command#343]
### Describe the bug:

I am using CLI to get a post list. More specifically, i just needs to get the post titles.
Post titles contain characters in Polish in their names, so they contain characters such as `ą`, `ó`, `ł`, `ż`, etc.

My command is: `wp post list --field=post_title --format=json`
The command works, post names are returned in json, but instead of Polish characters there is something like: `\u0141` , `\u00d3`, `\u017b`

If I use another type of format such as csv (`--format=csv`), all works fine

### Examples:

- #### `wp post list --field=post_title --format=json`:
   ![image](https://user-images.githubusercontent.com/30685349/151941979-7e6d160f-08aa-4aaf-8942-7dbdf221544f.png)

- #### `wp post list --field=post_title --format=csv`:
   ![image](https://user-images.githubusercontent.com/30685349/151942111-633bbec6-9d1c-498b-ab97-8d7fa64f2423.png)

### Additional screenshot:
![image](https://user-images.githubusercontent.com/30685349/151942556-b5f6b08a-2eb3-4a3a-a5c2-1d0bf8a2da80.png)

### Steps to reproduce:

Use command `wp post list --field=post_title --format=json`

### WordPress Environment:

- WordPress 5.8.2
- PHP 8.0.12
- Ubuntu 20.04 focal running on WSL2
- wp-config charset:

```
define( 'DB_CHARSET', 'utf8mb4' );
define( 'DB_COLLATE', '' );
```

### WP-CLI version:
- WP-CLI 2.5.0

**Comment by Sidsector9** [comment]
IMO this is by design in PHP. Generally, it is the job of the application that consumes the data to parse the data as necessary.

@schlessera do you think we should fix this in the command by using `JSON_UNESCAPED_UNICODE`?

**Comment by danielbachhuber** [comment]
Thanks for the report, @kanlukasz !

At this point, I don't think we'll change the behavior of `--format=json`. The risk of something else breaking is potentially large.

It looks like it's possible to unescape the unicode with [jq](https://stedolan.github.io/jq/):

```
$ wp post list --format=json
[{"ID":7,"post_title":"Testing og\u00f3rek","post_name":"","post_date":"2022-08-31 15:14:45","post_status":"draft"},{"ID":1,"post_title":"Hello world!","post_name":"hello-world","post_date":"2022-07-20 14:15:17","post_status":"publish"}]%
$ wp post list --format=json | jq .
[
  {
    "ID": 7,
    "post_title": "Testing ogórek",
    "post_name": "",
    "post_date": "2022-08-31 15:14:45",
    "post_status": "draft"
  },
  {
    "ID": 1,
    "post_title": "Hello world!",
    "post_name": "hello-world",
    "post_date": "2022-07-20 14:15:17",
    "post_status": "publish"
  }
]
```
