### ISSUE TITLE
`wp user create` ignores the `user_url` argument

### ISSUE THREAD

**Issue by kevin75001** [wp-cli/entity-command#350]
Hi,

When using command line `wp create user` with --user_url argument, the value is ignored.

Step to reproduce : 

`/usr/bin/php /usr/local/bin/wp-cli --path='/path/to/wordpress/' user create 'testurl' 'sample@email.com' --role='editor' --user_pass='strong_password' --first_name='first' --last_name='last' --user_url='http://www.testsite.com' --debug`

No error reported in debug.

Then :

`/usr/local/bin/wp-cli --path='/path/to/wordpress/' user get testurl --fields=user_url`

Return empty value instead of http://www.testsite.com

**Comment by chesio** [comment]
Hi @kevin75001,

in your example you set `--site_url`, not `--user_url`.

**Comment by kjohnson** [comment]
I can tackle this one.
