### ISSUE TITLE
Missing argument with `option patch update` should throw error

### ISSUE THREAD

**Issue by Diego-Schmidt** [wp-cli/entity-command#353]
Hello, I'm having problems using this commands to disable and enable the maintenance mode of a subsite.
If the maintenance mode is enabled and i send the command to disable it the result is:
wp --url=subsite.multisite.com --allow-root option patch update seedprod_settings '{"enable_maintenance_mode":"false"}' --format=json
Success: Updated 'seedprod_settings' option.

If i send the command to enable the maintenance mode again the result is:
wp --url=subsite.multisite.com --allow-root option patch update seedprod_settings '{"enable_maintenance_mode":"true"}' --format=json
PHP Warning:  json_decode() expects parameter 1 to be string, array given in /home/multisite.com/public_html/wp-content/plugins/coming-soon/app/render-csp-mm.php on line 36
array (
  'enable_maintenance_mode' => 'true',
)

And the seedprod_settings object settings dissapear from the subsite options. Any idea what can be happening here?
Thanks in advance for the support.

**Comment by Diego-Schmidt** [comment]
Any example with the correct command format ?

**Comment by danielbachhuber** [comment]
@Diego-Schmidt It would be something like this:

```
wp option patch update <key> <key-path>... [<value>]
```

Feel free to drop by `#cli` on [WordPress.org Slack](https://make.wordpress.org/chat/) if you'd like help with your particular use case.
