### ISSUE TITLE
`wp post list` with invalid `--post-status` returns some posts

### ISSUE THREAD

**Issue by jamieburchell** [wp-cli/entity-command#361]
## Bug Report

- [X] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [X] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

**Describe the current, buggy behavior**

When running the following command:

`wp post list --post_status=foo --format=ids`

Three posts IDs are returned pertaining to posts with the post statuses "publish", "publish" and "auto-draft" respectively. It doesn't seem to matter what invalid post type text is used in place of "foo".

**Describe how other contributors can replicate this bug**

- Run the command above

**Describe what you would expect as the correct outcome**

An error or no results.

**Let us know what environment you are running this on**

```
OS:     Linux 4.18.0-372.16.1.el8_6.x86_64 #1 SMP Wed Jul 13 15:36:40 UTC 2022 x86_64
Shell:  /bin/bash
PHP binary:     /usr/bin/php
PHP version:    8.0.22
php.ini used:   /etc/php.ini
MySQL binary:   /usr/bin/mysql
MySQL version:  mysql  Ver 15.1 Distrib 10.5.16-MariaDB, for Linux (x86_64) using  EditLine wrapper
SQL modes:
WP-CLI root dir:        phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:      phar://wp-cli.phar/vendor
WP_CLI phar path:       /var/www/releases/4
WP-CLI packages dir:
WP-CLI global config:
WP-CLI project config:  /var/www/releases/4/wp-cli.yml
WP-CLI version: 2.6.0
```

**Comment by danielbachhuber** [comment]
Hey @jamieburchell,

Thanks for the report!

I agree the behavior you're reporting is definitely unexpected. Unfortunately, WP-CLI simply passes the arguments through to `WP_Query`, and returns the data from `WP_Query`.

Given the broad range of arguments supported by `WP_Query`, it's unlikely we'll add query argument validation in WP-CLI.

**Comment by jamieburchell** [comment]
@danielbachhuber Fair enough. Curious why WP_Query would return results for a post type which doesn't exist

**Comment by danielbachhuber** [comment]
> Curious why `WP_Query` would return results for a post type which doesn't exist

@jamieburchell There are a lot of "less than desirable" behaviors in `WP_Query` 😁 

One of my favorites: if you pass `post__in=[]`, then you get all posts: https://core.trac.wordpress.org/ticket/28099

**Comment by jamieburchell** [comment]
@danielbachhuber Nice. I'd love to know what it was about the three posts it returned that were special.
