### ISSUE TITLE
wp option list --search="" not returning empty result

### ISSUE THREAD

**Issue by Diego-Schmidt** [wp-cli/entity-command#364]
Hello, I'm trying to use wp cli to list all sites using an option field but there is no output and no error. I'm using wp site option list --search="fieldname_*" but it is not returning anything. Thanks for the support in advance.

**Comment by BhargavBhandari90** [comment]
Do you want to list all sites from multisite? OR want to list options?

**Comment by BhargavBhandari90** [comment]
I quickly tried your command on my multisite and got this
![image](https://user-images.githubusercontent.com/19459637/185784978-f00c6ea1-4f72-4b09-b8b1-979c2263a165.png)

**Comment by Diego-Schmidt** [comment]
I was looking to list all sites on multisite containing a given option value. Can this be achieved using wp cli?

**Comment by BhargavBhandari90** [comment]
@Diego-Schmidt Try this `wp site list --field=url | xargs -n1 -I % wp site option list --search="admin_*" --url=%`

**Comment by Diego-Schmidt** [comment]
Using that command I'm getting this, multiple times, but no url.

| meta_key      | meta_value          |
+---------------+---------------------+
| admin_email   | admin@email.com |
| admin_user_id | 1                   |
+---------------+---------------------+

**Comment by BhargavBhandari90** [comment]
@Diego-Schmidt 

If you want site URLs, then there are 3 options.

**1**

`wp site list`

![image](https://user-images.githubusercontent.com/19459637/185851558-45d7740b-478e-45b7-9217-1ff2e8d50968.png)

---

**2**

`wp site list --field=url | xargs -n1 -I % wp option list --search="siteurl" --url=% `

Site URL is stored in `siteurl` meta key so make sure you search according to that.

![image](https://user-images.githubusercontent.com/19459637/185851790-cf57038d-404a-4ebb-87eb-1f208ccee5b6.png)

---

**3**

`wp site list --field=url | xargs -n1 -I % wp option get siteurl --url=%`

![image](https://user-images.githubusercontent.com/19459637/185852063-998ad08b-6591-4eaf-ac68-8dc9872d7536.png)

**Comment by danielbachhuber** [comment]
@Diego-Schmidt Feel free to drop into the `#cli` channel on WordPress.org Slack if you need more help figuring this out.
