### ISSUE TITLE
Deactivate a site on a multisite using url

### ISSUE THREAD

**Issue by Diego-Schmidt** [wp-cli/entity-command#369]
Hello, and thanks for any guide :D. Is there any known way to deactivate a subsite on a multisite using its url? for example
"wp site --url=subsite.mainsite.com deactivate"

**Comment by schlessera** [comment]
You'll have to switch around the approach to make use of `--url` here. It should work like this:
```bash
wp site deactivate $(wp eval 'echo get_current_blog_id();' --url=subsite.mainsite.com)
```
