### ISSUE TITLE
Application Passwords created with "wp user application-password create" timeout.

### ISSUE THREAD

**Issue by jdhoneatt** [wp-cli/entity-command#380]
Have found that Application Passwords generated with "wp user application-password create" do not work.  
When I try to test them with curl or postman request I get an error of, "Error Loading Site | 502 Bad Gateway".  
If I manually generate an application password on the user profile page and perform the same request, it works.  
This seems like an issue so I am reporting it and hoping to find a resolution.  
I have 360+ installs to create and capture application passwords for and would prefer not to have to use the ui on every install.

**Comment by danielbachhuber** [comment]
Thanks for the report, @jdhoneatt !

> Have found that Application Passwords generated with "wp user application-password create" do not work.
> When I try to test them with curl or postman request I get an error of, "Error Loading Site | 502 Bad Gateway".

It looks like we simply call a WordPress core method under the hood:

https://github.com/wp-cli/entity-command/blob/4c04786310f3a585cf34a7479b7856bdd8b09084/src/User_Application_Password_Command.php#L303-L315

A newly created application password seems to work for me using [httpie](https://httpie.io/):

```
$ wp user application-password create daniel test
Success: Created application password.
Password: bjfWPPtfIiOABooH6SwlkDMP
$ http -a daniel:bjfWPPtfIiOABooH6SwlkDMP https://vanilla.test/wp-json/wp/v2/users/me --verify=no
HTTP/1.1 200 OK
```

Can you share more details on the debugging you've done, or steps to reproduce?
