### ISSUE TITLE
clarify syntax to list multiple post IDs to delete

### ISSUE THREAD

**Issue by joeldcanfield** [wp-cli/entity-command#386]
Examples of how to delete posts only include a single ID deletion: 
[https://developer.wordpress.org/cli/commands/post/update/#examples](url)
leaving it unclear how multiple IDs should be listed.

Other example sections [https://developer.wordpress.org/cli/commands/post/update/#examples](url) make it clear that the list should be a space separated, not comma separated.

**Comment by danielbachhuber** [comment]
Thanks for the suggestion, @joeldcanfield !

I'm not 100% confident I know what you're referring to. Is there a specific example you'd recommend adding? Want to submit a pull request for it?

You should be able to even edit the file directly in GitHub:

https://github.com/wp-cli/entity-command/blob/main/src/Post_Command.php#L466-L481
