### ISSUE TITLE
wp post edit ignores system environment setting, launches vi(m) instead

### ISSUE THREAD

**Issue by joeldcanfield** [wp-cli/entity-command#389]
`wp post edit [ID]` should launch $EDITOR (the system editor specified in the system environment variables.)

instead, it launches vi(m).

discovered this three years ago but it took that long to remember how to quit vi(m) _<—yes, I'm joking_

Mac Monterey using default terminal

**Comment by danielbachhuber** [comment]
Thanks for the report, @joeldcanfield.

`wp post edit` uses `WP_CLI\Utils\launch_editor_for_input()` under the hood, which references the `EDITOR` environment variable:

https://github.com/wp-cli/wp-cli/blob/a584b19db7d6f813ed0e321f74c952875affcb30/php/utils.php#L424-L427

It will default to `vi` if no `EDITOR` is found.

Maybe `EDITOR` wasn't set when you thought it was? Does this issue still reproduce for you?

**Comment by joeldcanfield** [comment]
Ahem. If I'm logged into **my web server** via ssh, the editor launched will not be my local editor, right? 

No current local environment to test, but assume user error.

**Comment by danielbachhuber** [comment]
> If I'm logged into **my web server** via ssh, the editor launched will not be my local editor, right?

Correct. It will be the web server editor.
