### ISSUE TITLE
"wp post term set" do not set multiple term to the <id>

### ISSUE THREAD

**Issue by micabal** [wp-cli/entity-command#396]
I working on the WooCommerce extension. I try to set multiple categories to a product, however, the terms are not assigned as expected. The command is:

```
sudo wp post term set 342671 product_cat 'supports-publicitaires-affichage' 'cadres-porte-affiches-indoor' \
    --allow-root \
    --path='/srv/www/mywebsite/public_html'
```

Instead of setting the terms from the slugs <'supports-publicitaires-affichage' and 'cadres-porte-affiches-indoor'>, it sets properly 'supports-publicitaires-affichage' but creates a new term from 'cadres-porte-affiches-indoor'. The slug 'cadres-porte-affiches-indoor' is already existing in wp_terms, making a duplicate slug.

Please note that 'supports-publicitaires-affichage' is **the parent** of 'cadres-porte-affiches-indoor'.

Maybe I simply do not use properly the command. In this case, maybe some example to the [Developper Resource](https://developer.wordpress.org/cli/commands/post/term/set/) would be welcomed. 

Thanks a lot!

----
I tried also without sucess:
```
sudo wp post term set 342671 product_cat 'supports-publicitaires-affichage','cadres-porte-affiches-indoor' \
    --allow-root \
    --path='/srv/www/mywebsite/public_html'
```
```
sudo wp post term set 342671 product_cat supports-publicitaires-affichage,cadres-porte-affiches-indoor \
    --allow-root \
    --path='/srv/www/mywebsite/public_html'
```
```
sudo wp post term set 342671 product_cat '10376,3751' --by=id \
    --allow-root \
    --path='/srv/www/mywebsite/public_html'
```

**Comment by danielbachhuber** [comment]
@micabal Were you able to figure this out?

**Comment by micabal** [comment]
No. I did not figure out. I’ll try with next versions. It’s not critical for my case.
