### ISSUE TITLE
Add ability for reset-password method to print new password to STDOUT

### ISSUE THREAD

**Issue by ShaunR** [wp-cli/entity-command#397]
We are constantly having to access or reset a clients WordPress user password.  I would like to see an option to spit the newly generated password out to STDOUT.

Command would look something like this...
```
wp-cli user reset-password admin reset-password --skip-email --display
```

**Comment by danielbachhuber** [comment]
Thanks for the suggestion, @ShaunR

Closing in favor of https://github.com/wp-cli/entity-command/issues/342
