### ISSUE TITLE
Error when using double dollar sign as user's password

### ISSUE THREAD

**Issue by yogasukma** [wp-cli/entity-command#404]
## Bug Report

When creating user or update user, it always fail to login when we use password that has double or more dolar sign ($$).

example code  using one $, it will be fine:
```
wp user update user2 --user_pass="some$"
```

example code  using double $$:
```
wp user update user2 --user_pass="some$$"
```
it will cause issue, and user can't login using password `some$$`

but, if we use like this
```
wp user update user2 --user_pass="some\$\$"
```
it will be fine, and can login using `some$$`

no error show up, command will just complete like usual, just can't login using double dollar sign ($$)

wp cli version: `WP-CLI 2.7.1`

**Comment by chesio** [comment]
@yogasukma 

Try these two commands and you'll understand (that it's not WP-CLI issue):
```sh
echo "$$"
```
vs.
```sh
echo '$$'
```

**Comment by yogasukma** [comment]
Ah! right, really forgot about it!

you're right, thank you, will close it.
