### ISSUE TITLE
Can't use `wp user spam *ID*` on single site installation

### ISSUE THREAD

**Issue by Rvervuurt** [wp-cli/entity-command#412]
## Bug Report

- [√] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [√] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

**Describe the current, buggy behavior**

I'm trying to mark a user as spam with `wp user spam *ID*`, but I get the error `Error: This is not a multisite installation.`

**Describe how other contributors can replicate this bug**

- Create a clean WP installation
- Generate some users with `wp user generate`
- Try to mark a random user (f.ex. 50) as spam with `wp user spam 50`

**Describe what you would expect as the correct outcome**

I expect user 50 to be registered as spam, as the (docs)[https://developer.wordpress.org/cli/commands/user/spam/] make me think it should, no matter if it's a multiste or not.

**Let us know what environment you are running this on**

```
OS:	Darwin 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000 arm64
Shell:	/bin/zsh
PHP binary:	/opt/homebrew/Cellar/php@8.1/8.1.21/bin/php
PHP version:	8.1.21
php.ini used:	/opt/homebrew/etc/php/8.1/php.ini
MySQL binary:
MySQL version:
SQL modes:
WP-CLI root dir:	phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:	phar://wp-cli.phar/vendor
WP_CLI phar path:	/Applications/MAMP/htdocs/ideal/wordpress
WP-CLI packages dir:
WP-CLI cache dir:	/Users/robbert/.wp-cli/cache
WP-CLI global config:
WP-CLI project config:
WP-CLI version:	2.8.1
```

**Provide additional context/Screenshots**

<img width="452" alt="image" src="https://github.com/wp-cli/entity-command/assets/1439765/e0bf086a-cabc-4f06-80eb-7f199f03b8fc">

**Comment by danielbachhuber** [comment]
Hey @Rvervuurt,

The concept of marking a user as spam only exists in WordPress multisite:

**Multisite**

<img width="719" alt="image" src="https://github.com/wp-cli/entity-command/assets/36432/b1921898-7f3d-445f-b42a-9331fdd078bf">

**Standard**

<img width="411" alt="image" src="https://github.com/wp-cli/entity-command/assets/36432/53977834-6ca6-469d-9ce0-7d844d690985">

Whenever relevant, WP-CLI emulates wp-admin, so this isn't behavior we'll change.

How would you recommend we improve the documentation? Want to submit a PR with your suggested changes?

https://github.com/wp-cli/entity-command/blob/5c141092e7d0940c27da29408d6b67d9db1d3934/src/User_Command.php#L1214-L1248

**Comment by Rvervuurt** [comment]
Ah that makes sense! I didn't know it was multisite-only!

There must be other multisite-commands, how are they documented?

**Comment by danielbachhuber** [comment]
> There must be other multisite-commands, how are they documented?

@Rvervuurt That's a good question. They generally aren't explicitly documented as such, but usually have some reference to multisite:

https://github.com/wp-cli/entity-command/blob/5c141092e7d0940c27da29408d6b67d9db1d3934/src/Site_Command.php#L11

We could say something like:

```
Marks one or more users as spam on multisite.
```

Or:

```
Marks one or more users as spam.

Spam users only exist on multisite.
```

Do you have a preference? Or another suggestion?
