### ISSUE TITLE
Use `RecursiveDataStructureTraverser` from `wp-cli` package 

### ISSUE THREAD

**Issue by thelovekesh** [wp-cli/entity-command#435]
## Feature Request

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).

For reuse elsewhere, the `RecursiveDataStructureTraverser` and `NonExistentKeyException` classes(currently part of this package) have been moved to the `wp-cli` package in https://github.com/wp-cli/wp-cli/pull/5864.

Once these changes are live, we can safely deprecate or extend the logic from `wp-cli` package.

See https://github.com/wp-cli/wp-cli/issues/5837

**Comment by danielbachhuber** [comment]
We'll need to hold off on this until WP-CLI 2.10.0 (or 3.0.0) is released.

**Comment by thelovekesh** [comment]
@danielbachhuber Since this has landed in the WP CLI 2.10.0 release, I am closing this as done.
