### ISSUE TITLE
Define known fields as allowed arguments for `wp post (create|update)`

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/entity-command#44]
Same thing as #19, but for `wp post create` and `wp post update`.

Under the hood, both commands use `wp_insert_post()`. We should define `wp_insert_post()`'s arguments as allowed arguments for each command. `[--<field>=<value>]` should remain as an argument to accept additional arbitrary values.

**Comment by Sidsector9** [comment]
@danielbachhuber Should I list all known fields or the most common and put a link to `wp_insert_post()` for the remaining?

**Comment by danielbachhuber** [comment]
> Should I list all known fields or the most common ones

All known fields that are supported by WP-CLI.
