### ISSUE TITLE
Support --order=(asc|desc) and --orderby=(default|<key>) when listing options and meta

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/entity-command#45]
In `wp * meta list` and `wp option list`, we should support `--order=(asc|desc)` and `--orderby=(default|<key>)` arguments so the user has more control over the display of the results.

This might look like:

* `wp post meta list --orderby=meta_key --order=desc` - Display results ordered by `meta_key`.
* `wp option list --orderby=option_name --order=asc` - Display results ordered by `option_name`.

We'll likely need to perform these sorts in PHP because the underlying native WordPress APIs don't support these arguments.

Originally https://github.com/wp-cli/wp-cli/issues/4242

**Comment by BhargavBhandari90** [comment]
@danielbachhuber 

if `--orderby=meta_key` or `--orderby=option_name` is the only option for the meta/options list then we shouldn't add that into command.
However, we can sort `options list` by its `id` too.

**Comment by danielbachhuber** [comment]
> if `--orderby=meta_key` or `--orderby=option_name` is the only option for the meta/options list then we shouldn't add that into command.

There should be two options: `default` or `(meta_key|option_name)`

**Comment by danielbachhuber** [comment]
🔨
