### ISSUE TITLE
Accept User instead of user ID only for reassign in user delete command

### ISSUE THREAD

**Issue by ernilambar** [wp-cli/entity-command#488]
## Feature Request

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).

**Describe your use case and the problem you are facing**

Currently only User ID is accepted for `--reassign` in user delete command.

**Describe the solution you'd like**

Accept user login, user ID or user email.

**Comment by danielbachhuber** [comment]
@ernilambar Can you share a bit more context for this request? I'm a bit hesitant about what you've proposed because:
* It would technically be a breaking change.
* We'd potentially want to make a similar change to `wp post update --post_author=<id>`, but I don't think it makes sense to.

**Comment by ernilambar** [comment]
Please elaborate if I am not getting something but I dont think it would be breaking change as using ID are reassign value will continue to work like now. Along with ID we will accept login and email address as value like we do in other user commands. Under the hood, ID will be the actual value like WP core accepts. 
We treat User ID, User Login and User Email as unique user identifier. So I think it would be good improvement to make those uniform in our all commands.
