### ISSUE TITLE
Update `wp option` for new changes in trunk / WordPress 6.6

### ISSUE THREAD

**Issue by swissspidy** [wp-cli/entity-command#491]
## Feature Request

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).

**Describe your use case and the problem you are facing**

https://core.trac.wordpress.org/changeset/57920 got committed in trunk yesterday.

This caused some wp option tests to fail on trunk, see https://github.com/wp-cli/entity-command/actions/runs/8563704484/job/23469200909

**Describe the solution you'd like**

WP-CLI should support the new logic and tests should pass again.

**Comment by thelovekesh** [comment]
@swissspidy please feel free to assign to me. What's the ETA for this? Can this be fixed on contributor day?

**Comment by swissspidy** [comment]
No need for assignements, just start working on it whenever you are interested. Can be during hack day but also before or after.
