### ISSUE TITLE
Introduce wp site mature and wp site public

### ISSUE THREAD

**Issue by johnbillion** [wp-cli/entity-command#51]
Commands for marking a site as active/deactivated, archived/unarchived, spam/unspammed already exist. These change the site status via `update_blog_status()`.

Marking a site as mature/unmature and public/unpublic are missing (the terminology here is terrible). The following commands should be added for completeness:

* `wp site mature <id>`
* `wp site public <id>`

**Comment by Sidsector9** [comment]
@johnbillion, can we discuss about the terminologies? 

How does public/private and mature/(all|general) sound?

**Comment by Sidsector9** [comment]
#63

**Comment by danielbachhuber** [comment]
🔨
