### ISSUE TITLE
Need document update in User_Command.php file

### ISSUE THREAD

**Issue by Umangvaghela** [wp-cli/entity-command#52]
Need document update in User_Command.php file

**Comment by miya0001** [comment]
Related:
https://github.com/wp-cli/entity-command/pull/53#pullrequestreview-57466092

**Comment by Umangvaghela** [comment]
@miya0001 

I know WordPress Provide default user functionality.I want to say why we are user <role> and [<role>].Can we use one of them to maintain the consistency?

**Comment by miya0001** [comment]
Ah, let's talk at https://github.com/wp-cli/entity-command/issues/52, if you have more details.
