### ISSUE TITLE
wp site delete -- idiot-proof against deleting root blog

### ISSUE THREAD

**Issue by tommcgee57** [wp-cli/entity-command#66]
I'd like to suggest setting a test for which blog to delete, so that you don't accidentally delete the root blog the way I did! I had a function, feeding a value into site-delete, with the plan to delete several hundred blogs at a time (passing the --yes flag to the command). 

But I  got distracted and didn't notice what the return value was going to be. It was "1".  

Maybe it shouldn't be possible to delete the blog that matches BLOG_ID_CURRENT_SITE.

**Comment by schlessera** [comment]
I think that makes sense. If you're trying to delete the `BLOG_ID_CURRENT_SITE` site, we could exit with a warning and only allow the operation to go through with a `--force` or `--delete-root` flag.

**Comment by danielbachhuber** [comment]
What sort of warning UI does WordPress core display when deleting the root blog? Whenever possible, WP-CLI should mirror the behavior of WordPress core.

Also, does deleting the root blog cause WordPress to behave differently than deleting any other blog?

**Comment by tommcgee57** [comment]
Not sure about what WordPress core does, but after it’s deleted in WP-CLI when you go to the home page of the multisite blog (let’s say, http://www.multisiteblog.net) it throws a 404 error. Worse, going to http://www.multisiteblog.net/wp-admin or http://www.multisiteblog.net/wp-admin/network also throws a 404 error.

I was able to get into the back end with http://www.multisiteblog.net/somesub-blog/wp-admin, then navigating to the network admin page from there.

**Comment by johnbillion** [comment]
> What sort of warning UI does WordPress core display when deleting the root blog? Whenever possible, WP-CLI should mirror the behavior of WordPress core.

Core doesn't allow the root blog to be deleted. There is no means by which a user can retrieve a valid nonce for deleting the root blog, therefore there's no failure or confirmation UI.

**Comment by miya0001** [comment]
> Core doesn't allow the root blog to be deleted. 

Ah, the behavior should be like following?

```
When I try `wp site delete 1`
Then STDERR should be:
  """
  Error: You can't delete root blog.
  """
And the return code should be 0
```

**Comment by johnbillion** [comment]
Yep I think it should :+1:

**Comment by miya0001** [comment]
Thanks @johnbillion 

The plan in #73 is trying to add `--delete-root` option and it allows to delete root blog.
I think we don't need `--delete-root` and it should return error when we try to delete root blog.

@wp-cli/committers Is it ok?

**Comment by Sidsector9** [comment]
@miya0001 , I think that's the only way to do it since WP won't allow root blog to be deleted. I have made the necessary changes in #73
