### ISSUE TITLE
Improve 'wp menu' command description in

### ISSUE THREAD

**Issue by hearvox** [wp-cli/entity-command#67]
Improve command description in:
https://github.com/wp-cli/entity-command/blob/master/src/Menu_Command.php
Command: wp menu
Current description: List, create, assign, and delete menus.

Proposed description:
Manages menus for the WordPress site.

Lists, creates, assigns, and deletes the active theme's [navigation menus](https://developer.wordpress.org/themes/functionality/navigation-menus/).

**Comment by miya0001** [comment]
Related:
https://github.com/wp-cli/wp-cli/issues/4302

**Comment by BhargavBhandari90** [comment]
> Lists, creates, assigns, and deletes the active theme's navigation menus.

Should this line also need to be added?

**Comment by hearvox** [comment]
I added that line so we could include a link the Nav Menus page in the Theme Handbook. Might make it easier for folk wanting to see that reference page. Also, The Docs team always tells me it's good to take opportunities to interlink different Handbooks, when appropriate.

**Comment by danielbachhuber** [comment]
👍 to inter-handbook linking.

I think "Lists, creates, assigns, and deletes the active theme's navigation menus." makes most sense as the command short description, and then we can include a longer description with the handbook links too.

**Comment by hearvox** [comment]
So maybe, Proposed description:
Lists, creates, assigns, and deletes the active theme's navigation menus.

See the [Navigation Menus](https://developer.wordpress.org/themes/functionality/navigation-menus/) reference in the Theme Handbook.
