### ISSUE TITLE
Improve 'wp network' command description

### ISSUE THREAD

**Issue by hearvox** [wp-cli/entity-command#68]
(Note: This command has no description now: Don't think it has a truth-src file.
There's is for its subcommand:
https://github.com/wp-cli/entity-command/blob/master/src/Network_Meta_Command.php
Should we create Network_Command.php a file in the entity-command repo?)

Command: wp network
Current description: (none)

Proposed description:
Manages meta fields for multisite networks.

**Comment by miya0001** [comment]
Related:
https://github.com/wp-cli/wp-cli/issues/4302

**Comment by danielbachhuber** [comment]
The problem here is that WP-CLI doesn't have a way of registering a description for a namespace.

Because there's no top-level command at `wp network`, there's no description parsed.

We'll need to address https://github.com/wp-cli/wp-cli/issues/4385 first.

**Comment by danielbachhuber** [comment]
Handled in #105
