### ISSUE TITLE
Improve 'wp option' command description

### ISSUE THREAD

**Issue by hearvox** [wp-cli/entity-command#69]
Improve command description in:
https://github.com/wp-cli/entity-command/blob/master/src/Option_Command.php
Command: wp option
Current description: Manage options.

Proposed description:
Retrieves and sets site options, including plugin and WordPress settings.

See the [Plugin Settings API](https://developer.wordpress.org/plugins/settings/settings-api/) and the 
[Theme Options](https://developer.wordpress.org/themes/customize-api/) for more information on adding customized options.

**Comment by miya0001** [comment]
Related:
https://github.com/wp-cli/wp-cli/issues/4302

**Comment by danielbachhuber** [comment]
This was handled in #83
