### ISSUE TITLE
Improve 'wp post-type' command description

### ISSUE THREAD

**Issue by hearvox** [wp-cli/entity-command#71]
Improve command description in:
https://github.com/wp-cli/entity-command/blob/master/src/Post_Type_Command.php
Command: wp post-type
Current description: Manage post types.

Proposed description:
Retrieves details on the site's registered post-types.

Get details on WordPress built-in and [custom post types](https://developer.wordpress.org/plugins/post-types/).

**Comment by miya0001** [comment]
Related:
https://github.com/wp-cli/wp-cli/issues/4302

**Comment by BhargavBhandari90** [comment]
@miya0001 @hearvox 

How about `Get list of registered post type and detailed info about it` ?

**Comment by miya0001** [comment]
I don't know, I am not good at English very well. 😄

**Comment by BhargavBhandari90** [comment]
Me as well. Well, let's see if @hearvox has to say anything about this.

**Comment by hearvox** [comment]
"Retrieves..." is the verb most often used in the Codex and the Code Reference, so I'm trying to keep that consistent across handbooks. As to what's retrieved, the words used most often are "details", "data", or "information" -- which in most cases refers both a list of the items (like post-types), or details about an item (like info about a single post-type).
https://developer.wordpress.org/reference/functions/get_post/
