### ISSUE TITLE
wp option get active_plugins 

### ISSUE THREAD

**Issue by Jonduglus** [wp-cli/entity-command#76]
To use **wp option get active_plugins**  --format=json is required so add [--format=<format>] as --format=<format>. Beacause When I use this command without format that time no response display on CMD.

**Comment by miya0001** [comment]
I tried same command, but I couldn't see your problem.

Could you give us the result of `wp --info`?

**Comment by Umangvaghela** [comment]
@miya0001 

To use this command. **wp option get active_plugins**  without format.
Display no response.

**Comment by mitraval192** [comment]
Hello @miya0001

To use **wp option get active_plugins** without pass format parameter.

Thanks

**Comment by schlessera** [comment]
There's no problem with running this command without the `--format=json` argument, so I assume there must be a problem with your environment/install.

Also, it looks like you're using multiple accounts to work on GitHub. Please only use one account when contributing to WP-CLI, to avoid confusion and misunderstandings.
