### ISSUE TITLE
wp user session commands use incorrect terminology

### ISSUE THREAD

**Issue by johnbillion** [wp-cli/entity-command#84]
The `wp user session` commands use the word "token" in several places. This is incorrect, as the data being described is actually the "verifier", which is different from the token.

The session token identifies the session, but is not persistently stored. It's only stored in a user's auth and logged_in cookies. `wp user session` does not deal with the token, but the verifier, which is a one-way hash of the token, and which is stored persistently.

If a user tries to interact with the `wp user session` command using a token instead of a verifier, they're going to have a hard time and may wonder why nothing works, especially if they cross-reference things with the `WP_Session_Tokens` class in core.

**Comment by miya0001** [comment]
I agree but we have an option like following.

```
$ wp session list --fields=token
```

If we change the `token` to `verifier`, it will be breaking change. 😓

**Comment by johnbillion** [comment]
> If we change the token to verifier, it will be breaking change. 😓

Yep. I'm not sure how best to address this. See #85.

**Comment by schlessera** [comment]
So the `verifier` is a hash of the `token`. Would it be "good enough" to add something like this to the command's documentation?

```
Note: The `token` field does not return the actual token, but a hash of it. The real token is not persisted and can only be found in the corresponding cookies on the client side.
```

**Comment by johnbillion** [comment]
Yeah that sounds like a better approach than introducing a breaking change.
