### ISSUE TITLE
Add a positional argument to get primary site in multisite

### ISSUE THREAD

**Issue by Sidsector9** [wp-cli/entity-command#87]
As of now we don't have any means to get the primary site using WP-CLI
We can have a command as `wp site list --primary` to get the name and ID of the primary site that is set at Dashboard > My Sites

**Comment by BhargavBhandari90** [comment]
@Sidsector9 I saw that every site in multi-site has their own primary site. 
So I think we need an extra parameter of `--blog_id=*` in command for which site's primary site we want to get.

Please correct if I am missing anything here.

**Comment by danielbachhuber** [comment]
> As of now we don't have any means to get the primary site using WP-CLI

@Sidsector9 @BhargavBhandari90 I think `wp user meta get <id> primary_blog` is sufficient?

```bash
$ wp user meta get 1 primary_blog
1
```

If it's not, can you share a bit more detail about what you're trying to accomplish?

**Comment by BhargavBhandari90** [comment]
@danielbachhuber Yes, we can have it by the command you mentioned. @Sidsector9 do you have any input here?

**Comment by Sidsector9** [comment]
Agreeing with both. Closing in favour of Daniel's suggestion.

**Comment by danielbachhuber** [comment]
Added some docs for it with #365
