### ISSUE TITLE
wp post create (with <file> param) -- longer length content is cut-off/truncated in wordpress past ~20.5K chars

### ISSUE THREAD

**Issue by firxworx** [wp-cli/entity-command#88]
I am experiencing an issue with using `wp post create` to make longer posts/pages in conjunction with the `[file]` option to specify the filename of a source text file. 

Unless I've missed it, the docs do not mention anything about file sizes. 

I have confirmed that the input text files are fine and not truncated. The "wp post create" command executes successfully and returns an ID. The post/page appears in wordpress but the content is cut short. Longer posts/pages are consistently cut off (truncated) at about 20.5K characters. 

Wordpress itself has no problem creating the full-length posts/pages when I copy and paste the content from the input text files into the editor via the wp admin.

I figure the issue has to be with wp-cli. I tried searching online but couldn't find anyone with a similar complaint. 

My scripts are essentially executing something to the effect of: 

`(sudo -u wwwuser -- wp post create $CONTENTFILE --post_type=page --post_parent=$PARENT --post_title="$TITLE" --post_status=publish --path=$WPPATH --porcelain)`

- The input text file is UTF-8 encoded.
- I made sure there was plenty of memory available
- I had this issue with 1.2.1. Just now I upgraded to latest/1.3.0 and the issue remains the same
- Very stock LAMP server setup on Ubuntu 16.04.x
- If I play with the command try to `cat` the file and pipe it to a modified version of the above `wp post create...` command with the file argument `-` (which tells wp-cli to read from stdin) the issue is identical.

**Comment by gitlost** [comment]
I can't reproduce this using a 300K text file. WP-CLI just does a `file_get_contents()` of the file (and then calls the WP core function `wp_insert_post()`) so there are no file size limits as far as it's concerned.

**Comment by firxworx** [comment]
Thanks for the replication attempt. I appreciate the detail re how wp-cli uses file_get_contents() under the hood, it was insightful. I spun up a VM w/ a bare wordpress and have not been able to replicate there either. There's something funny with the affected setup, as close to stock as it may be, but at this point its likely not wp-cli.
