### ISSUE TITLE
`wp user remove-cap` incorrectly returns success status when attempting to remove cap inherited from a role

### ISSUE THREAD

**Issue by johnbillion** [wp-cli/entity-command#97]
Given a user with a role of Editor, running `wp user remove-cap publish_posts <user>` will incorrectly show a success message stating that the capability has been removed.

Attempting to remove any capability which is not directly assigned to the user (most capabilities are inherited from the user's role) will incorrectly result in a success message.

**Comment by danielbachhuber** [comment]
Thanks for the report, @johnbillion. What would your expected behavior (and message) be in this case?

**Comment by johnbillion** [comment]
I think the expected behaviour in this case is to return an error. The best way to phrase it might be to say that the capability cannot be removed from the user because it's inherited from the user's role.

**Comment by johnbillion** [comment]
Alternatively: This could add the capability with a value of `false`, which explicitly denies the capability for the user, overriding their role (AFAIK, I'll need to triple check this). Or that could result in even more unexpected behaviour. Could be an option via a flag, eg `--force-deny`?

**Comment by danielbachhuber** [comment]
I think it makes more sense to return an error here.

**Comment by schlessera** [comment]
I agree, an error makes more sense. Adding a `wp user override-cap` is still an option for the second proposed behavior.
