### ISSUE TITLE
Need a way to distinguish between a user's direct capabilities and those inherited from their role

### ISSUE THREAD

**Issue by johnbillion** [wp-cli/entity-command#99]
`wp user list-roles <user>` returns both the capabilities that a user has been directly assigned, and the capabilities that they inherit from their role.

Their doesn't appear to be a way to retrieve only a list of the user's direct capabilities. It would be nice to have this option via a flag.

**Comment by schlessera** [comment]
Option A:
`--direct--only` and `--inherited-only`, both mutually exclusive

Option B:
`--origin=direct|inherited|all`

Hmm, both don't look right to me. Did I miss the obvious one?

**Comment by johnbillion** [comment]
`--origin=user|role|all` could work.
